export function expenseTaxCopy(locale: "en" | "sv") {
  return locale === "sv" ? sv : en;
}
const en = {
  title: "Expense tax review",
  value: "Value",
  boundary:
    "Record source observations and accountant review separately. This does not post an expense or prepare a VAT return. Source coverage and ledger reconciliation remain unestablished.",
  actualBlocked:
    "No production-approved Swedish tax profile or rounding rule is enabled. Actual-company records remain excluded from supported contributions, even after review. No income or employees does not establish zero VAT.",
  synthetic: "Synthetic demonstration",
  actual: "Actual-company review",
  sourceClass: "Record class",
  sourceTitle: "Source observations",
  reviewTitle: "Accountant facts",
  sourceKey: "Stable source component key",
  sourceLocator: "Locator within source evidence",
  description: "Description",
  evidenceId: "Retained evidence ID",
  sourceEvidence: "Retain source or review evidence",
  evidenceTitle: "Evidence title",
  evidenceOrigin: "Evidence origin",
  evidenceContent: "Evidence text",
  evidenceSaved: "Evidence retained. Use this ID in the relevant facts.",
  createSource: "Record expense source",
  reviseSource: "Append source revision",
  reviewSource: "Record accountant review",
  sourceSaved: "Source revision retained. A new source revision needs a new review.",
  reviewSaved: "Reviewer facts retained. This is not tax activation or posting approval.",
  gross: "Gross (minor units)",
  net: "Net (minor units)",
  vat: "VAT (minor units)",
  unknown: "Unknown",
  nullable:
    "Leave unknown values blank. Enter monetary values as exact integer minor units, not formatted currency. Blank is not zero.",
  currency: "Source currency (three-letter code)",
  currencyScale: "Source currency scale",
  supplierJurisdiction: "Supplier jurisdiction (two-letter code)",
  supplyJurisdiction: "Supply jurisdiction (two-letter code)",
  bookJurisdiction: "Reviewed book jurisdiction (two-letter code)",
  issuedOn: "Invoice issue date",
  receivedOn: "Invoice receipt date",
  suppliedOn: "Supply date",
  taxPointOn: "Tax point date",
  changeSetId: "Related kernel proposal ID",
  voucherId: "Related kernel voucher ID",
  optionalRefs:
    "Optional proposal/voucher references must cite this source evidence. No invoice or ledger record is created here.",
  rationale: "Review rationale",
  registration: "Reviewed VAT registration",
  registered: "Registered",
  notRegistered: "Not registered",
  registrationEvidenceId: "Registration evidence ID",
  method: "Reviewed accounting method",
  accrual: "Accrual",
  cash: "Cash",
  methodEvidenceId: "Method evidence ID",
  dateBasis: "Basis for supply and tax dates",
  dateEvidenceId: "Date-basis evidence ID",
  treatment: "Named treatment",
  domesticPurchase: "Domestic purchase",
  foreignPurchase: "Foreign purchase — unsupported",
  reverseCharge: "Reverse charge — unsupported",
  imports: "Import — unsupported",
  exempt: "Exempt — unsupported",
  outOfScope: "Out of scope — unsupported",
  other: "Other — unsupported",
  profileId: "Named profile ID",
  profileVersion: "Profile version",
  rateNumerator: "Tax rate numerator",
  rateDenominator: "Tax rate denominator",
  deductionNumerator: "Deduction fraction numerator",
  deductionDenominator: "Deduction fraction denominator",
  deductionBasis: "Deduction basis",
  deductionEvidenceId: "Deduction-basis evidence ID",
  roundingPolicy: "Rounding policy",
  exactOnly: "Exact division only; reject fractional minor units",
  profileHelp:
    "Only synthetic-expense-tax version 1 can demonstrate calculations. Supply the rational rate and deduction fraction explicitly. They are not legal rates or permission to deduct.",
  inventory: "Retained expense sources",
  refresh: "Refresh",
  open: "Open",
  empty: "No sources are retained. Coverage is unknown; this is not a zero-VAT conclusion.",
  currentReview: "Review covers this source revision",
  staleReview: "Missing or stale review",
  history: "Immutable history",
  sourceRevision: "Source revision",
  reviewRevision: "Review revision",
  reviewedBy: "Recorded by",
  digest: "Digest",
  prepareSnapshot: "Freeze accountant review snapshot",
  snapshots: "Saved review snapshots",
  startsOn: "Interval start",
  endsOn: "Interval end",
  mode: "Snapshot mode",
  snapshotSaved: "Immutable review snapshot retained. Nothing was posted or filed.",
  included: "Synthetic contributions included",
  excluded: "Excluded source components",
  totals: "Synthetic demonstration totals only",
  deductible: "Deductible (minor units)",
  nonDeductible: "Nondeductible (minor units)",
  expense: "Expense (minor units)",
  controls: "Exact controls",
  sourceColumn: "Source",
  reviewColumn: "Reviewer",
  calculatedColumn: "Calculated (synthetic only)",
  amountColumn: "Amount",
  difference: "Difference (minor units)",
  sourceBalanceDifferenceMinor: "Source gross − net − VAT",
  reviewBalanceDifferenceMinor: "Reviewed gross − net − VAT",
  grossDifferenceMinor: "Reviewed gross − source gross",
  netDifferenceMinor: "Reviewed net − source net",
  vatDifferenceMinor: "Reviewed VAT − source VAT",
  calculatedVatDifferenceMinor: "Reviewed VAT − calculated VAT",
  excludedReasons: "Exclusion reasons",
  calculation: "Exact rational calculation",
  remainder: "Remainder",
  download: "Download review JSON",
  fresh: "Source/reviewer basis is current",
  stale: "Source/reviewer basis changed. This snapshot stays immutable.",
  next: "Next page",
  first: "First page",
  cancel: "Close editor",
  invalid:
    "Review required fields, real dates, exact integer amounts and reference IDs. Your entries are retained.",
  operatorOnly:
    "Only an operator can record accountant review facts. This role does not establish professional or legal approval.",
  sourceKeyHelp:
    "Use one key per source component. Recover the existing key after an uncertain result instead of creating a duplicate.",
  newSource: "Record another source",
  newEvidence: "Retain another evidence item",
  openProposal: "Open kernel proposal",
  noSnapshots: "No review snapshots retained.",
};
const sv: typeof en = {
  title: "Granska moms på utgifter",
  value: "Värde",
  boundary:
    "Bevara källuppgifter och redovisningsgranskning separat. Detta bokför ingen utgift och skapar ingen momsdeklaration. Underlagens fullständighet och avstämning mot huvudboken är inte fastställda.",
  actualBlocked:
    "Ingen produktionsgodkänd svensk skatteprofil eller avrundningsregel är aktiverad. Verkliga företagsuppgifter utesluts från beräkningsbidrag även efter granskning. Avsaknad av intäkter eller anställda visar inte att momsen är noll.",
  synthetic: "Syntetisk demonstration",
  actual: "Granskning av verkligt företag",
  sourceClass: "Uppgiftsklass",
  sourceTitle: "Källuppgifter",
  reviewTitle: "Granskarens uppgifter",
  sourceKey: "Stabil nyckel för källkomponenten",
  sourceLocator: "Plats i underlaget",
  description: "Beskrivning",
  evidenceId: "ID för bevarat underlag",
  sourceEvidence: "Bevara käll- eller granskningsunderlag",
  evidenceTitle: "Underlagets titel",
  evidenceOrigin: "Underlagets ursprung",
  evidenceContent: "Underlagets text",
  evidenceSaved: "Underlaget har bevarats. Använd detta ID i relevanta uppgifter.",
  createSource: "Registrera utgiftskälla",
  reviseSource: "Lägg till källversion",
  reviewSource: "Registrera granskarens uppgifter",
  sourceSaved: "Källversionen har bevarats. En ny källversion behöver en ny granskning.",
  reviewSaved:
    "Granskarens uppgifter har bevarats. Detta aktiverar ingen skatteprofil och godkänner ingen bokföring.",
  gross: "Brutto (minsta valutaenhet)",
  net: "Netto (minsta valutaenhet)",
  vat: "Moms (minsta valutaenhet)",
  unknown: "Okänt",
  nullable:
    "Lämna okända värden tomma. Ange belopp som exakta heltal i minsta valutaenhet, inte formaterad valuta. Tomt är inte noll.",
  currency: "Källans valuta (trebokstavskod)",
  currencyScale: "Källans valutaskala",
  supplierJurisdiction: "Leverantörens jurisdiktion (tvåbokstavskod)",
  supplyJurisdiction: "Leveransens jurisdiktion (tvåbokstavskod)",
  bookJurisdiction: "Granskad bokjurisdiktion (tvåbokstavskod)",
  issuedOn: "Fakturadatum",
  receivedOn: "Fakturans ankomstdatum",
  suppliedOn: "Leveransdatum",
  taxPointOn: "Beskattningstidpunkt",
  changeSetId: "ID för kopplat bokföringsförslag",
  voucherId: "ID för kopplad verifikation",
  optionalRefs:
    "Valfria förslags- och verifikationsreferenser måste hänvisa till detta underlag. Ingen faktura eller bokföring skapas här.",
  rationale: "Granskningsmotivering",
  registration: "Granskad momsregistrering",
  registered: "Registrerad",
  notRegistered: "Inte registrerad",
  registrationEvidenceId: "ID för registreringsunderlag",
  method: "Granskad redovisningsmetod",
  accrual: "Faktureringsmetod",
  cash: "Kontantmetod",
  methodEvidenceId: "ID för metodunderlag",
  dateBasis: "Grund för leverans- och beskattningsdatum",
  dateEvidenceId: "ID för datumunderlag",
  treatment: "Namngiven behandling",
  domesticPurchase: "Inhemskt inköp",
  foreignPurchase: "Utländskt inköp — stöds inte",
  reverseCharge: "Omvänd skattskyldighet — stöds inte",
  imports: "Import — stöds inte",
  exempt: "Undantag — stöds inte",
  outOfScope: "Utanför tillämpningsområdet — stöds inte",
  other: "Annat — stöds inte",
  profileId: "Namngivet profil-ID",
  profileVersion: "Profilversion",
  rateNumerator: "Skattesatsens täljare",
  rateDenominator: "Skattesatsens nämnare",
  deductionNumerator: "Avdragsandelens täljare",
  deductionDenominator: "Avdragsandelens nämnare",
  deductionBasis: "Avdragsgrund",
  deductionEvidenceId: "ID för avdragsunderlag",
  roundingPolicy: "Avrundningspolicy",
  exactOnly: "Endast exakt division; avvisa bråkdelar av minsta valutaenheten",
  profileHelp:
    "Endast synthetic-expense-tax version 1 kan demonstrera beräkningar. Ange rationell skattesats och avdragsandel uttryckligen. De är inte lagstadgade satser eller tillstånd till avdrag.",
  inventory: "Bevarade utgiftskällor",
  refresh: "Uppdatera",
  open: "Öppna",
  empty: "Inga källor har bevarats. Fullständigheten är okänd; detta innebär inte noll moms.",
  currentReview: "Granskningen gäller denna källversion",
  staleReview: "Granskning saknas eller är inaktuell",
  history: "Oföränderlig historik",
  sourceRevision: "Källversion",
  reviewRevision: "Granskningsversion",
  reviewedBy: "Registrerad av",
  digest: "Kontrollsumma",
  prepareSnapshot: "Spara periodgranskning",
  snapshots: "Sparade granskningsunderlag",
  startsOn: "Intervallets början",
  endsOn: "Intervallets slut",
  mode: "Underlagets läge",
  snapshotSaved:
    "Granskningsunderlaget har bevarats oföränderligt. Inget har bokförts eller lämnats in.",
  included: "Inkluderade syntetiska bidrag",
  excluded: "Uteslutna källkomponenter",
  totals: "Summor endast för syntetisk demonstration",
  deductible: "Avdragsgillt (minsta valutaenhet)",
  nonDeductible: "Inte avdragsgillt (minsta valutaenhet)",
  expense: "Utgift (minsta valutaenhet)",
  controls: "Exakta kontroller",
  sourceColumn: "Källa",
  reviewColumn: "Granskare",
  calculatedColumn: "Beräknat (endast syntetiskt)",
  amountColumn: "Belopp",
  difference: "Differens (minsta valutaenhet)",
  sourceBalanceDifferenceMinor: "Källans brutto − netto − moms",
  reviewBalanceDifferenceMinor: "Granskat brutto − netto − moms",
  grossDifferenceMinor: "Granskat brutto − källans brutto",
  netDifferenceMinor: "Granskat netto − källans netto",
  vatDifferenceMinor: "Granskad moms − källans moms",
  calculatedVatDifferenceMinor: "Granskad moms − beräknad moms",
  excludedReasons: "Orsaker till uteslutning",
  calculation: "Exakt rationell beräkning",
  remainder: "Rest",
  download: "Hämta granskning som JSON",
  fresh: "Käll- och granskningsgrunden är aktuell",
  stale: "Käll- eller granskningsgrunden har ändrats. Underlaget förblir oföränderligt.",
  next: "Nästa sida",
  first: "Första sidan",
  cancel: "Stäng redigeringen",
  invalid:
    "Kontrollera obligatoriska fält, riktiga datum, exakta heltalsbelopp och referens-ID. Dina värden finns kvar.",
  operatorOnly:
    "Endast en operatör kan registrera granskarens uppgifter. Rollen innebär inte professionellt eller juridiskt godkännande.",
  sourceKeyHelp:
    "Använd en nyckel per källkomponent. Hämta den befintliga nyckeln efter ett osäkert svar i stället för att skapa en dubblett.",
  newSource: "Registrera en annan källa",
  newEvidence: "Bevara ytterligare underlag",
  openProposal: "Öppna bokföringsförslag",
  noSnapshots: "Inga granskningsunderlag har bevarats.",
};
