-- effect-mq 0.7.0 PostgreSQL store; names mirror its schema factories.
CREATE TABLE public.effect_mq_jobs (
  id text PRIMARY KEY, name text NOT NULL, queue text NOT NULL, state text NOT NULL,
  priority integer NOT NULL DEFAULT 0, seq bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  payload jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  attempts_max integer NOT NULL, attempts_made integer NOT NULL DEFAULT 0,
  stalled_count integer NOT NULL DEFAULT 0, backoff jsonb, keep jsonb,
  timeout_ms bigint, cancel_requested boolean NOT NULL DEFAULT false,
  dedupe_key text, trace jsonb, parent jsonb, flow_fail_fast boolean,
  flow_pending integer, flow_completed integer, flow_failed integer, flow_cancelled integer,
  run_at timestamptz NOT NULL, enqueued_at timestamptz NOT NULL,
  processed_at timestamptz, finished_at timestamptz, exit jsonb,
  failed_reason text, lock_token text, lock_expires_at timestamptz
);
CREATE INDEX effect_mq_jobs_ready_idx ON public.effect_mq_jobs(queue, priority DESC, seq ASC) WHERE state = 'waiting';
CREATE INDEX effect_mq_jobs_delayed_idx ON public.effect_mq_jobs(queue, run_at) WHERE state = 'delayed';
CREATE INDEX effect_mq_jobs_active_idx ON public.effect_mq_jobs(lock_expires_at) WHERE state = 'active';
CREATE INDEX effect_mq_jobs_history_idx ON public.effect_mq_jobs(name, state, finished_at);
CREATE INDEX effect_mq_jobs_listing_idx ON public.effect_mq_jobs(enqueued_at DESC, id DESC);
CREATE INDEX effect_mq_jobs_metadata_idx ON public.effect_mq_jobs USING gin(metadata jsonb_path_ops);
CREATE TABLE public.effect_mq_job_attempts (
  job_id text NOT NULL REFERENCES public.effect_mq_jobs(id) ON DELETE CASCADE,
  attempt integer NOT NULL, outcome text NOT NULL,
  started_at timestamptz, finished_at timestamptz NOT NULL, exit jsonb,
  PRIMARY KEY(job_id, attempt)
);
CREATE TABLE public.effect_mq_schedules (
  key text PRIMARY KEY, job_name text NOT NULL, queue text NOT NULL,
  cron text, tz text, every_ms bigint, payload jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb, priority integer NOT NULL DEFAULT 0,
  attempts_max integer NOT NULL, backoff jsonb, keep jsonb, timeout_ms bigint,
  group_name text, next_run_at timestamptz NOT NULL
);
CREATE INDEX effect_mq_schedules_due_idx ON public.effect_mq_schedules(next_run_at);
CREATE TABLE public.effect_mq_queue_control (queue text PRIMARY KEY, paused boolean NOT NULL DEFAULT false);
CREATE TABLE public.effect_mq_dedupe (
  name text NOT NULL, key text NOT NULL, job_id text NOT NULL,
  window_expires_at timestamptz, PRIMARY KEY(name, key)
);
CREATE TABLE public.effect_mq_flow_children (
  flow_id text NOT NULL, child_key text NOT NULL, name text NOT NULL,
  store_key text NOT NULL, spec jsonb NOT NULL, status text NOT NULL,
  exit jsonb, failed_reason text, cascaded boolean NOT NULL,
  pending_since timestamptz NOT NULL, PRIMARY KEY(flow_id, child_key)
);
CREATE INDEX effect_mq_flow_children_pending_idx ON public.effect_mq_flow_children(pending_since) WHERE status = 'pending';
CREATE INDEX effect_mq_flow_children_cascade_idx ON public.effect_mq_flow_children(flow_id) WHERE status = 'cancelled' AND NOT cascaded;
CREATE TABLE public.effect_mq_flow_outbox (
  id bigserial PRIMARY KEY, flow_name text NOT NULL,
  parent_store_key text NOT NULL, report jsonb NOT NULL
);
REVOKE ALL ON public.effect_mq_jobs, public.effect_mq_job_attempts,
  public.effect_mq_schedules, public.effect_mq_queue_control, public.effect_mq_dedupe,
  public.effect_mq_flow_children, public.effect_mq_flow_outbox FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.effect_mq_jobs, public.effect_mq_job_attempts,
  public.effect_mq_schedules, public.effect_mq_queue_control, public.effect_mq_dedupe,
  public.effect_mq_flow_children, public.effect_mq_flow_outbox TO openerp_runtime;
GRANT USAGE, SELECT ON SEQUENCE public.effect_mq_jobs_seq_seq,
  public.effect_mq_flow_outbox_id_seq TO openerp_runtime;
