const english = {
  title: "Technical period lock",
  ownerTax: "Owner and expense review checks",
  legacyProviderScope:
    "Historical basis: owner and expense-review dependencies were not captured by this version.",
  ownerReviewCounts: "Unresolved owner reviews / unlinked sources",
  expenseReviewCount: "Missing or stale expense reviews",
  expenseKnownCount: "Known expense sources without supported posting/reconciliation coverage",
  unpaidAllowed:
    "Unpaid linked owner claims are allowed. Unknown openings, company completeness and tax eligibility remain unresolved.",
  warning:
    "Synthetic records only. Locking a period is not a statutory close, an annual report, or proof that company records are complete. No filing is sent.",
  period: "Accounting period",
  load: "Review period",
  refresh: "Refresh",
  locked: "Locked",
  open: "Open",
  inventory: "Declare expected bank sources",
  inventoryHelp:
    "Enter every expected synthetic bank account ID, separated by commas. An empty list explicitly declares no bank sources. Retain inventory evidence first. Other company obligations remain unknown.",
  bankAccounts: "Expected bank account IDs",
  evidence: "Retained inventory evidence ID",
  declare: "Save bank-source declaration",
  confirmInventory:
    "I declare that this list includes every expected bank source for this synthetic period.",
  declared: "Declaration saved",
  missingInventory: "No bank-source inventory declared.",
  checks: "Live technical prerequisites",
  check: "Check",
  detail: "Scope",
  passed: "Passed",
  blocked: "Blocked",
  statutory: "Statutory readiness remains blocked",
  reason: "Reason for this transition",
  close: "Prepare technical lock",
  reopen: "Prepare reopen",
  reopenHelp:
    "Reopening invalidates technical certificates and report readiness for this and later dependent periods. It does not alter old journals or report snapshots.",
  proposalId: "Period proposal ID",
  loadProposal: "Load proposal",
  review: "Review exact proposal",
  digest: "Proposal digest",
  approval: "Approve this exact period transition",
  confirm:
    "I reviewed the period, reason, source declaration, checks and dependency snapshot. This is a technical transition only.",
  execute: "Commit approved transition",
  stale: "Dependencies changed or could not be refreshed. Prepare and approve a new proposal.",
  current: "Dependencies match the proposal.",
  receipt: "Committed transition receipt",
  version: "Period version",
  invalidated: "Invalidated certificates / reports",
  history: "Transition history",
  emptyHistory: "No committed period transitions.",
  next: "Next history page",
  first: "First history page",
  certificate: "Technical certificate",
  currentCertificate: "Current technical lock evidence",
  invalidCertificate: "Historical certificate — no longer current",
  viewCertificate: "Inspect certificate",
  immutable: "Historical records are retained unchanged.",
  invalid: "Check the required fields and identifiers.",
  pending: "Working…",
  action: "Action",
  approvedBy: "Approved by",
  expires: "Approval expires",
  closeAction: "Technical lock",
  reopenAction: "Reopen",
  snapshot: "Captured prerequisites",
  dependencies: "Dependency snapshot",
  inventorySaved: "Declared bank accounts",
  none: "Explicitly none",
  prepareHelp:
    "Prepare a proposal, review it, approve its exact digest, then commit. Approval expires after15 minutes.",
};
const swedish: typeof english = {
  title: "Teknisk periodlåsning",
  ownerTax: "Kontroller av ägar- och utgiftsgranskning",
  legacyProviderScope:
    "Historiskt underlag: denna version sparade inte beroenden för ägar- och utgiftsgranskning.",
  ownerReviewCounts: "Olösta ägargranskningar / källor utan bokföringslänk",
  expenseReviewCount: "Saknade eller inaktuella utgiftsgranskningar",
  expenseKnownCount: "Kända utgiftskällor utan stödd bokförings- och avstämningstäckning",
  unpaidAllowed:
    "Obetalda, bokföringslänkade ägarfordringar är tillåtna. Ingående balans, företagets fullständighet och skatterättslig bedömning är fortfarande olösta.",
  warning:
    "Endast syntetiska poster. En låst period är inte ett lagstadgat bokslut, en årsredovisning eller bevis på att företagets underlag är fullständiga. Ingen inlämning skickas.",
  period: "Redovisningsperiod",
  load: "Granska period",
  refresh: "Uppdatera",
  locked: "Låst",
  open: "Öppen",
  inventory: "Ange förväntade bankkällor",
  inventoryHelp:
    "Ange alla förväntade syntetiska bankkonto-ID:n, avgränsade med kommatecken. En tom lista anger uttryckligen att inga bankkällor finns. Spara underlaget först. Övriga skyldigheter är fortfarande okända.",
  bankAccounts: "Förväntade bankkonto-ID:n",
  evidence: "ID för sparat källförteckningsunderlag",
  declare: "Spara bankkällförteckning",
  confirmInventory:
    "Jag intygar att listan innehåller alla förväntade bankkällor för den syntetiska perioden.",
  declared: "Förteckningen har sparats",
  missingInventory: "Ingen bankkällförteckning har angetts.",
  checks: "Aktuella tekniska förutsättningar",
  check: "Kontroll",
  detail: "Omfattning",
  passed: "Godkänd",
  blocked: "Blockerad",
  statutory: "Lagstadgad beredskap är fortfarande blockerad",
  reason: "Orsak till ändringen",
  close: "Förbered teknisk låsning",
  reopen: "Förbered återöppning",
  reopenHelp:
    "En återöppning gör tekniska intyg och rapportberedskap inaktuella för denna och senare beroende perioder. Gamla verifikationer och rapportögonblicksbilder ändras inte.",
  proposalId: "ID för periodförslag",
  loadProposal: "Hämta förslag",
  review: "Granska det exakta förslaget",
  digest: "Förslagets kontrollsumma",
  approval: "Godkänn exakt denna periodändring",
  confirm:
    "Jag har granskat period, orsak, källförteckning, kontroller och beroenden. Detta är endast en teknisk ändring.",
  execute: "Verkställ godkänd ändring",
  stale:
    "Beroenden har ändrats eller kunde inte uppdateras. Förbered och godkänn ett nytt förslag.",
  current: "Beroendena stämmer med förslaget.",
  receipt: "Kvitto på genomförd ändring",
  version: "Periodversion",
  invalidated: "Inaktuella intyg / rapporter",
  history: "Ändringshistorik",
  emptyHistory: "Inga genomförda periodändringar.",
  next: "Nästa historiksida",
  first: "Första historiksidan",
  certificate: "Tekniskt intyg",
  currentCertificate: "Aktuellt underlag för teknisk låsning",
  invalidCertificate: "Historiskt intyg — inte längre aktuellt",
  viewCertificate: "Granska intyg",
  immutable: "Historiska poster bevaras oförändrade.",
  invalid: "Kontrollera obligatoriska fält och ID:n.",
  pending: "Arbetar…",
  action: "Åtgärd",
  approvedBy: "Godkänt av",
  expires: "Godkännandet löper ut",
  closeAction: "Teknisk låsning",
  reopenAction: "Återöppning",
  snapshot: "Sparade förutsättningar",
  dependencies: "Beroendeögonblicksbild",
  inventorySaved: "Angivna bankkonton",
  none: "Uttryckligen inga",
  prepareHelp:
    "Förbered ett förslag, granska det, godkänn den exakta kontrollsumman och verkställ sedan. Godkännandet gäller i15 minuter.",
};
export function closingCopy(locale: string) {
  return locale === "sv" ? swedish : english;
}
