const english = {
  familyInventory: "Family applicability and controls",
  familyScope: "This technical scope requires a decision for every family.",
  legacyFamilyScope: "Historical bank-only scope. No complete family inventory was captured.",
  familyHelp:
    "Choose every decision. Not applicable needs dated evidence and cannot override represented records. Required unavailable controls block closing. No values are assumed.",
  familyStatus: "Applicability decision",
  familyDate: "Reviewed on",
  familyEvidence: "Decision evidence ID",
  familyRationale: "Decision rationale",
  familyRevision: "Inventory revision",
  familyMissing: "Not declared",
  familyUnavailable: "Unavailable",
  familyLabels: {
    bank_sources: "Bank sources",
    invoices: "Invoices and open items",
    tax: "Tax periods and accounts",
    payroll: "Payroll and declarations",
    assets_deferrals: "Assets and deferrals",
    foreign_currency: "Foreign currency",
    owner_balances: "Owner balances",
    other_balances: "Other material balances",
    external_schedules: "External schedules",
    disclosures: "Required disclosures",
  },
  familyStatuses: {
    required: "Required",
    not_applicable: "Not applicable — evidenced decision",
    unsupported: "Unsupported",
    unknown: "Unknown",
  },

  title: "Technical period lock",
  ownerTax: "Owner and tax review checks",
  vatReviewCounts: "Represented VAT fact components / saved drafts",
  vatDependency: "VAT source and ledger basis digest",
  vatBoundary:
    "These are book-wide represented records, not complete period coverage. Any facts or drafts contradict tax not applicable; required tax controls remain unavailable.",
  legacyVatScope:
    "Historical basis: this snapshot did not capture VAT return dependencies. No missing VAT counts are assumed to be zero.",
  legacyProviderScope:
    "Historical basis: owner and expense-review dependencies were not captured by this version.",
  ownerReviewCounts: "Unresolved owner reviews / unlinked sources",
  expenseReviewCount: "Missing or stale expense reviews",
  expenseKnownCount: "Known expense sources without supported posting/reconciliation coverage",
  unpaidAllowed:
    "Unpaid linked owner claims are allowed. Unknown openings, company completeness and tax eligibility remain unresolved.",
  warning:
    "Synthetic records only. Locking a period is not a statutory close, an annual report, or proof that company records are complete. No filing is sent.",
  period: "Accounting period",
  load: "Review period",
  refresh: "Refresh",
  locked: "Locked",
  open: "Open",
  inventory: "Declare period obligations",
  inventoryHelp:
    "Declare each family explicitly and retain the evidence first. Enter every expected bank account ID, separated by commas. An empty bank list does not declare other obligations absent.",
  bankAccounts: "Expected bank account IDs",
  evidence: "Retained inventory evidence ID",
  declare: "Save obligation inventory",
  confirmInventory:
    "I reviewed every family and its evidence for this synthetic period. This is not a statutory signoff.",
  declared: "Declaration saved",
  missingInventory: "No bank-source inventory declared.",
  checks: "Live technical prerequisites",
  check: "Check",
  detail: "Scope",
  passed: "Passed",
  blocked: "Blocked",
  statutory: "Statutory readiness remains blocked",
  reason: "Reason for this transition",
  close: "Prepare technical lock",
  reopen: "Prepare reopen",
  reopenHelp:
    "Reopening invalidates technical certificates and report readiness for this and later dependent periods. It does not alter old journals or report snapshots.",
  proposalId: "Period proposal ID",
  loadProposal: "Load proposal",
  review: "Review exact proposal",
  digest: "Proposal digest",
  approval: "Approve this exact period transition",
  confirm:
    "I reviewed the period, reason, source declaration, checks and dependency snapshot. This is a technical transition only.",
  execute: "Commit approved transition",
  stale: "At the last successful refresh, dependencies had changed. Prepare and approve a new proposal.",
  current: "At the last successful refresh, dependencies matched the proposal.",
  currentnessUnknown: "Current status is unknown. Retained facts remain available; new actions need a successful refresh.",
  retryRequest: "Retry sends the same captured request and key. A failed refresh does not show whether the transition committed.",
  retryApproval: "Retry the same approval request",
  retryExecution: "Retry the same transition request",
  receipt: "Committed transition receipt",
  version: "Period version",
  invalidated: "Invalidated certificates / reports",
  history: "Transition history",
  emptyHistory: "No committed period transitions.",
  next: "Next history page",
  first: "First history page",
  certificate: "Technical certificate",
  currentCertificate: "Technical lock evidence matched at the last successful refresh.",
  invalidCertificate: "Historical certificate — not current at the last successful refresh.",
  viewCertificate: "Inspect certificate",
  immutable: "Historical records are retained unchanged.",
  invalid: "Check the required fields and identifiers.",
  pending: "Working…",
  action: "Action",
  approvedBy: "Approved by",
  expires: "Approval expires",
  closeAction: "Technical lock",
  reopenAction: "Reopen",
  snapshot: "Captured prerequisites",
  dependencies: "Dependency snapshot",
  inventorySaved: "Declared bank accounts",
  none: "Explicitly none",
  prepareHelp:
    "Prepare a proposal, review it, approve its exact digest, then commit. Approval expires after15 minutes.",
};
const swedish: typeof english = {
  familyInventory: "Områden och kontroller",
  familyScope: "Denna tekniska omfattning kräver ett beslut för varje område.",
  legacyFamilyScope: "Historiskt bankunderlag. Ingen fullständig områdesförteckning sparades.",
  familyHelp:
    "Välj varje beslut. Ej tillämpligt kräver daterat underlag och kan inte åsidosätta registrerade poster. Nödvändiga kontroller som saknas blockerar låsning. Inga värden antas.",
  familyStatus: "Tillämplighetsbeslut",
  familyDate: "Granskat den",
  familyEvidence: "Beslutets underlags-ID",
  familyRationale: "Beslutets motivering",
  familyRevision: "Förteckningsversion",
  familyMissing: "Ej deklarerat",
  familyUnavailable: "Saknas",
  familyLabels: {
    bank_sources: "Bankkällor",
    invoices: "Fakturor och öppna poster",
    tax: "Skatteperioder och skattekonton",
    payroll: "Löner och deklarationer",
    assets_deferrals: "Tillgångar och periodiseringar",
    foreign_currency: "Utländsk valuta",
    owner_balances: "Ägarsaldon",
    other_balances: "Andra väsentliga saldon",
    external_schedules: "Externa sammanställningar",
    disclosures: "Nödvändiga upplysningar",
  },
  familyStatuses: {
    required: "Krävs",
    not_applicable: "Ej tillämpligt — styrkt beslut",
    unsupported: "Stöds inte",
    unknown: "Okänt",
  },

  title: "Teknisk periodlåsning",
  ownerTax: "Kontroller av ägar- och skattegranskning",
  vatReviewCounts: "Registrerade momskomponenter / sparade utkast",
  vatDependency: "Kontrollsumma för momsunderlag och huvudbok",
  vatBoundary:
    "Detta är registrerade poster i hela boken, inte fullständig periodtäckning. Fakta eller utkast motsäger att skatt inte är tillämplig; nödvändiga skattekontroller saknas fortfarande.",
  legacyVatScope:
    "Historiskt underlag: ögonblicksbilden sparade inte momsdeklarationens beroenden. Saknade momsantal antas inte vara noll.",
  legacyProviderScope:
    "Historiskt underlag: denna version sparade inte beroenden för ägar- och utgiftsgranskning.",
  ownerReviewCounts: "Olösta ägargranskningar / källor utan bokföringslänk",
  expenseReviewCount: "Saknade eller inaktuella utgiftsgranskningar",
  expenseKnownCount: "Kända utgiftskällor utan stödd bokförings- och avstämningstäckning",
  unpaidAllowed:
    "Obetalda, bokföringslänkade ägarfordringar är tillåtna. Ingående balans, företagets fullständighet och skatterättslig bedömning är fortfarande olösta.",
  warning:
    "Endast syntetiska poster. En låst period är inte ett lagstadgat bokslut, en årsredovisning eller bevis på att företagets underlag är fullständiga. Ingen inlämning skickas.",
  period: "Redovisningsperiod",
  load: "Granska period",
  refresh: "Uppdatera",
  locked: "Låst",
  open: "Öppen",
  inventory: "Ange periodens skyldigheter",
  inventoryHelp:
    "Ange varje område uttryckligen och spara underlaget först. Ange alla förväntade bankkonto-ID:n, avgränsade med kommatecken. En tom banklista innebär inte att andra skyldigheter saknas.",
  bankAccounts: "Förväntade bankkonto-ID:n",
  evidence: "ID för sparat källförteckningsunderlag",
  declare: "Spara skyldighetsförteckning",
  confirmInventory:
    "Jag har granskat varje område och dess underlag för den syntetiska perioden. Detta är inte ett lagstadgat godkännande.",
  declared: "Förteckningen har sparats",
  missingInventory: "Ingen bankkällförteckning har angetts.",
  checks: "Aktuella tekniska förutsättningar",
  check: "Kontroll",
  detail: "Omfattning",
  passed: "Godkänd",
  blocked: "Blockerad",
  statutory: "Lagstadgad beredskap är fortfarande blockerad",
  reason: "Orsak till ändringen",
  close: "Förbered teknisk låsning",
  reopen: "Förbered återöppning",
  reopenHelp:
    "En återöppning gör tekniska intyg och rapportberedskap inaktuella för denna och senare beroende perioder. Gamla verifikationer och rapportögonblicksbilder ändras inte.",
  proposalId: "ID för periodförslag",
  loadProposal: "Hämta förslag",
  review: "Granska det exakta förslaget",
  digest: "Förslagets kontrollsumma",
  approval: "Godkänn exakt denna periodändring",
  confirm:
    "Jag har granskat period, orsak, källförteckning, kontroller och beroenden. Detta är endast en teknisk ändring.",
  execute: "Verkställ godkänd ändring",
  stale:
    "Vid den senaste lyckade uppdateringen hade beroendena ändrats. Förbered och godkänn ett nytt förslag.",
  current: "Vid den senaste lyckade uppdateringen stämde beroendena med förslaget.",
  currentnessUnknown: "Aktuell status är okänd. Sparade uppgifter finns kvar; nya åtgärder kräver en lyckad uppdatering.",
  retryRequest: "Försöket skickar samma sparade begäran och nyckel. En misslyckad uppdatering visar inte om ändringen genomfördes.",
  retryApproval: "Försök med samma godkännandebegäran igen",
  retryExecution: "Försök med samma ändringsbegäran igen",
  receipt: "Kvitto på genomförd ändring",
  version: "Periodversion",
  invalidated: "Inaktuella intyg / rapporter",
  history: "Ändringshistorik",
  emptyHistory: "Inga genomförda periodändringar.",
  next: "Nästa historiksida",
  first: "Första historiksidan",
  certificate: "Tekniskt intyg",
  currentCertificate: "Underlaget för teknisk låsning stämde vid den senaste lyckade uppdateringen.",
  invalidCertificate: "Historiskt intyg — inte aktuellt vid den senaste lyckade uppdateringen.",
  viewCertificate: "Granska intyg",
  immutable: "Historiska poster bevaras oförändrade.",
  invalid: "Kontrollera obligatoriska fält och ID:n.",
  pending: "Arbetar…",
  action: "Åtgärd",
  approvedBy: "Godkänt av",
  expires: "Godkännandet löper ut",
  closeAction: "Teknisk låsning",
  reopenAction: "Återöppning",
  snapshot: "Sparade förutsättningar",
  dependencies: "Beroendeögonblicksbild",
  inventorySaved: "Angivna bankkonton",
  none: "Uttryckligen inga",
  prepareHelp:
    "Förbered ett förslag, granska det, godkänn den exakta kontrollsumman och verkställ sedan. Godkännandet gäller i15 minuter.",
};
export function closingCopy(locale: string) {
  return locale === "sv" ? swedish : english;
}
