export const english = {
  title: "Company admission",
  intro:
    "Each capability is checked against the date that capability uses. An unresolved capability is not a failure of the whole company.",
  refresh: "Check again",
  family: "Capability",
  selectorDate: "Checked on",
  status: "Result",
  admitted: "Admitted",
  incomplete: "Not admitted yet",
  noDate: "No date supplied",
  gap: "What is missing",
  blocks: "Operations it blocks",
  none: "Nothing is missing for this date.",
  ownerBound: "Owned elsewhere",
  ownerBoundHint:
    "This capability is activated by its own named owner. Record its evidence there, not here.",
  unknown_fact: "No reviewed fact",
  ambiguous_fact: "Several reviewed facts apply",
  unreviewed_fact: "Recorded but not independently reviewed",
  missing_rule_release: "No reviewed rule release covers this date",
  ambiguous_rule_release: "Several rule releases cover this date",
  inapplicable_release: "The reviewed release does not apply to this company",
  missing_role_binding: "No reviewed account role for this date",
  ambiguous_role_binding: "Several account roles apply to this date",
  inactive_account: "The bound account is not active",
  stale_role_binding: "The bound account changed after it was reviewed",
  missing_activation: "Not activated for this date",
  overlapping_activation: "Several activations overlap this date",
};

export const swedish = {
  title: "Företagsbehörighet",
  intro:
    "Varje funktion kontrolleras mot det datum som just den funktionen använder. En funktion som inte är beviljad är inte ett fel för hela företaget.",
  refresh: "Kontrollera igen",
  family: "Funktion",
  selectorDate: "Kontrollerat",
  status: "Resultat",
  admitted: "Beviljad",
  incomplete: "Inte beviljad än",
  noDate: "Inget datum angivet",
  gap: "Vad som saknas",
  blocks: "Åtgärder som blockeras",
  none: "Inget saknas för detta datum.",
  ownerBound: "Ägs av annan funktion",
  ownerBoundHint:
    "Den här funktionen aktiveras av sin egen namngivna ägare. Registrera underlaget där, inte här.",
  unknown_fact: "Ingen granskad uppgift",
  ambiguous_fact: "Flera granskade uppgifter gäller",
  unreviewed_fact: "Registrerad men inte oberoende granskad",
  missing_rule_release: "Ingen granskad regelrelease täcker detta datum",
  ambiguous_rule_release: "Flera regelreleases täcker detta datum",
  inapplicable_release: "Den granskade releasen gäller inte detta företag",
  missing_role_binding: "Ingen granskad kontoroll för detta datum",
  ambiguous_role_binding: "Flera kontrollerroller gäller detta datum",
  inactive_account: "Det bundna kontot är inte aktivt",
  stale_role_binding: "Kontot ändrades efter granskningen",
  missing_activation: "Inte aktiverad för detta datum",
  overlapping_activation: "Flera aktiveringar överlappar detta datum",
};
