import type { Locale } from "@/paraglide/runtime";
const en = {
  title: "Retain and review bank CSV",
  scope:
    "Observed sources only. This is not required-source coverage, accounting classification or proof that company records are complete. No posting or automatic matching occurs.",
  limits:
    "Supported profile: UTF-8 bank_csv_utf8_v1. Maximum 64 KiB, 200 data records, 32 columns and 4000 bytes per field. Current observation admission supports synthetic-core-v1 books only.",
  retain: "Retain original file",
  file: "Original CSV file",
  sourceSystem: "Source system",
  sourceAccountId: "Source bank account identity",
  occurrenceKey: "Stable occurrence identity",
  sourceRevision: "Source revision identity",
  identityHelp:
    "Use the same occurrence and revision identities when retrying the same acquisition. Distinct occurrences can share bytes. Do not use a content hash as the occurrence identity.",
  inventory: "Retained occurrences",
  refresh: "Refresh",
  first: "First page",
  next: "Next page",
  load: "Open retained source",
  empty: "No retained source occurrences on this page. This does not mean no sources are required.",
  invalid: "Review all required fields and supported values.",
  invalidFile: "Select a nonempty file of at most 65536 bytes.",
  readFailure: "Could not read the file. No new file was sent.",
  original: "Original bytes",
  download: "Download original file",
  downloadReceipt: "Download admission receipt",
  downloadPreview: "Download immutable preview",
  preview: "Create immutable preview",
  previewHelp:
    "Enter exact header names. Every row must be interpreted; unused columns remain retained and need review. Amounts must have no spaces or thousands separators. Header and data order are preserved.",
  choose: "Choose explicitly",
  delimiter: "Column delimiter",
  comma: "Comma",
  semicolon: "Semicolon",
  tab: "Tab",
  lineEnding: "Record line endings",
  lf: "LF",
  crlf: "CRLF",
  dateColumn: "Date header",
  descriptionColumn: "Description header",
  amountColumn: "Signed amount header",
  providerIdColumn: "Provider ID header (blank means none)",
  dateFormat: "Date format",
  decimalSeparator: "Decimal separator",
  dot: "Dot",
  sign: "Sign meaning",
  inflow_positive: "Positive means inflow",
  outflow_positive: "Positive means outflow",
  accountId: "Book account",
  currency: "Declared currency",
  currencyScale: "Declared currency scale",
  startsOn: "Interval starts",
  endsOn: "Interval ends",
  openingMinor: "Declared opening balance (minor units)",
  closingMinor: "Declared closing balance (minor units)",
  declaredComplete: "I explicitly declare the supplied interval complete",
  basis: "Coverage basis and known gaps",
  controlsHelp:
    "Enter independent declared balances, not inferred balances. An unchecked completeness declaration means incomplete, not unknown or zero. Currency scale 2 means 100 minor units per currency unit.",
  previewId: "Retained preview identity",
  openPreview: "Open selected preview",
  ready: "No blocking diagnostics. Operator review is still required.",
  blocked: "Blocked. No observations can be admitted from this preview.",
  stale: "Dependencies changed. Create and review a new preview.",
  unknown: "Current state is unavailable. Refresh before acting.",
  bom: "UTF-8 BOM present",
  structuralComplete: "All CSV records parsed",
  yes: "Yes",
  no: "No",
  diagnostics: "Diagnostics",
  code: "Code",
  record: "CSV record",
  line: "Physical line",
  bytes: "Byte range (start inclusive, end exclusive)",
  fields: "Retained field values",
  rows: "Normalized observations",
  date: "Date",
  description: "Description",
  amount: "Signed minor units",
  provider: "Provider identity",
  movement: "Valid-row movement total (minor units)",
  mapping: "Reviewed mapping and declarations",
  edit: "Use this mapping for a new preview",
  digest: "Preview digest",
  operator:
    "Only an operator can approve and admit an interpretation. The approving operator must perform admission.",
  review:
    "I reviewed the original bytes, every record, unused columns, mapping, sign, dates, currency, controls and coverage declaration.",
  rationale: "Review rationale",
  approve: "Approve this exact preview",
  expires: "Approval expires",
  admit: "Admit reviewed observations",
  admitted: "Observations admitted. This did not post or match any ledger lines.",
  receipt: "Admission receipt",
  statement: "Bank statement",
  different: "This occurrence was admitted through another retained preview.",
  plainUnavailable:
    "The original cannot be displayed as UTF-8 text. Download its exact bytes and inspect the retained diagnostics.",
  reason: "Message",
  previous: "Previous rows",
  range: "Row page",
  approvalHelp:
    "Approval expires after one hour. If admission outcome is uncertain, retry without changing the input, or refresh this source to recover its durable receipt.",
};
const sv = {
  title: "Bevara och granska bank-CSV",
  scope:
    "Endast observerade källor. Detta är inte en förteckning över obligatoriska källor, bokföringsklassificering eller bevis på fullständigt företagsunderlag. Ingen bokföring eller automatisk matchning sker.",
  limits:
    "Profil: UTF-8 bank_csv_utf8_v1. Högst 64 KiB, 200 datarader, 32 kolumner och 4000 byte per fält. Import av observationer stöder för närvarande endast synthetic-core-v1.",
  retain: "Bevara originalfil",
  file: "CSV-originalfil",
  sourceSystem: "Källsystem",
  sourceAccountId: "Bankkontots källidentitet",
  occurrenceKey: "Stabil identitet för källförekomsten",
  sourceRevision: "Källans revisionsidentitet",
  identityHelp:
    "Återanvänd förekomst- och revisionsidentiteter vid nytt försök för samma hämtning. Olika förekomster kan ha samma byte. Använd inte innehållshashen som förekomstidentitet.",
  inventory: "Bevarade förekomster",
  refresh: "Uppdatera",
  first: "Första sidan",
  next: "Nästa sida",
  load: "Öppna bevarad källa",
  empty: "Inga bevarade källförekomster på denna sida. Det betyder inte att inga källor behövs.",
  invalid: "Kontrollera obligatoriska fält och tillåtna värden.",
  invalidFile: "Välj en fil med 1–65536 byte.",
  readFailure: "Filen kunde inte läsas. Ingen ny fil skickades.",
  original: "Originalbyte",
  download: "Hämta originalfil",
  downloadReceipt: "Hämta importkvitto",
  downloadPreview: "Hämta oföränderlig förhandsgranskning",
  preview: "Skapa oföränderlig förhandsgranskning",
  previewHelp:
    "Ange exakta kolumnrubriker. Varje rad måste tolkas. Oanvända kolumner bevaras och ska granskas. Belopp får inte ha blanksteg eller tusentalsavgränsare. Rubriker och radordning bevaras.",
  choose: "Välj uttryckligen",
  delimiter: "Kolumnavgränsare",
  comma: "Komma",
  semicolon: "Semikolon",
  tab: "Tabb",
  lineEnding: "Radslut",
  lf: "LF",
  crlf: "CRLF",
  dateColumn: "Datumrubrik",
  descriptionColumn: "Beskrivningsrubrik",
  amountColumn: "Rubrik för belopp med tecken",
  providerIdColumn: "Rubrik för leverantörens rad-ID (tomt betyder inget)",
  dateFormat: "Datumformat",
  decimalSeparator: "Decimalavgränsare",
  dot: "Punkt",
  sign: "Tecknets betydelse",
  inflow_positive: "Positivt betyder inflöde",
  outflow_positive: "Positivt betyder utflöde",
  accountId: "Bokföringskonto",
  currency: "Angiven valuta",
  currencyScale: "Angivet antal valutadecimaler",
  startsOn: "Intervall från",
  endsOn: "Intervall till",
  openingMinor: "Angivet ingående saldo (minsta valutaenhet)",
  closingMinor: "Angivet utgående saldo (minsta valutaenhet)",
  declaredComplete: "Jag anger uttryckligen att underlaget för intervallet är fullständigt",
  basis: "Grund för täckning och kända luckor",
  controlsHelp:
    "Ange oberoende saldon, inte härledda saldon. En omarkerad fullständighetsförklaring betyder ofullständigt, inte okänt eller noll. Två valutadecimaler innebär 100 minsta enheter per valutaenhet.",
  previewId: "Förhandsgranskningens identitet",
  openPreview: "Öppna vald förhandsgranskning",
  ready: "Inga blockerande fel. Operatörsgranskning krävs fortfarande.",
  blocked: "Blockerad. Inga observationer kan importeras från denna förhandsgranskning.",
  stale: "Beroenden har ändrats. Skapa och granska en ny förhandsgranskning.",
  unknown: "Aktuellt tillstånd är inte tillgängligt. Uppdatera innan du fortsätter.",
  bom: "UTF-8-BOM finns",
  structuralComplete: "Alla CSV-poster har tolkats",
  yes: "Ja",
  no: "Nej",
  diagnostics: "Diagnostik",
  code: "Kod",
  record: "CSV-post",
  line: "Fysisk rad",
  bytes: "Byteintervall (från inklusive, till exklusive)",
  fields: "Bevarade fältvärden",
  rows: "Normaliserade observationer",
  date: "Datum",
  description: "Beskrivning",
  amount: "Minsta valutaenheter med tecken",
  provider: "Leverantörens radidentitet",
  movement: "Summa giltiga rörelser (minsta valutaenhet)",
  mapping: "Granskad mappning och deklarationer",
  edit: "Använd mappningen för ny förhandsgranskning",
  digest: "Förhandsgranskningens hash",
  operator:
    "Endast en operatör kan godkänna och importera en tolkning. Samma operatör måste godkänna och importera.",
  review:
    "Jag har granskat originalbyte, varje post, oanvända kolumner, mappning, tecken, datum, valuta, kontrollsaldon och täckningsförklaringen.",
  rationale: "Motivering till granskningen",
  approve: "Godkänn exakt denna förhandsgranskning",
  expires: "Godkännandet upphör",
  admit: "Importera granskade observationer",
  admitted: "Observationer importerade. Inga bokföringsrader skapades eller matchades.",
  receipt: "Importkvitto",
  statement: "Bankutdrag",
  different: "Förekomsten importerades via en annan bevarad förhandsgranskning.",
  plainUnavailable:
    "Originalet kan inte visas som UTF-8-text. Hämta originalbyte och granska bevarad diagnostik.",
  reason: "Meddelande",
  previous: "Föregående rader",
  range: "Radsida",
  approvalHelp:
    "Godkännandet gäller en timme. Vid osäkert importresultat: försök igen utan att ändra indata, eller uppdatera källan för att hämta det beständiga kvittot.",
} satisfies Record<keyof typeof en, string>;
export function intakeCopy(locale: Locale) {
  return locale === "sv" ? sv : en;
}
