import type { Locale } from "@/paraglide/runtime";

const en = {
  title: "Retain source documents",
  scope:
    "Observed sources only. This is not required-source coverage, accounting classification or proof that company records are complete. No posting or automatic matching occurs.",
  retainedOnly:
    "Original retained. Bank CSV interpretation supports CSV files up to 64 KiB; other documents remain available for download.",
  limits:
    "Supported profile: UTF-8 bank_csv_utf8_v1. Maximum 64 KiB, 200 data records, 32 columns and 4000 bytes per field. Current observation admission supports synthetic-core-v1 books only.",
  retain: "Retain original file",
  file: "Original file",
  sourceSystem: "Source system",
  sourceAccountId: "Source account identity",
  occurrenceKey: "Stable occurrence identity",
  sourceRevision: "Source revision identity",
  identityHelp:
    "Use the same occurrence and revision identities when retrying the same acquisition. Distinct occurrences can share bytes. Do not use a content hash as the occurrence identity.",
  inventory: "Retained occurrences",
  refresh: "Refresh",
  first: "First page",
  next: "Next page",
  load: "Open retained source",
  empty: "No retained source occurrences on this page. This does not mean no sources are required.",
  invalid: "Review all required fields and supported values.",
  invalidFile: "Select a nonempty file of at most 5 MiB.",
  readFailure: "Could not read the file. No new file was sent.",
  original: "View original file",
  download: "Download original file",
  downloadReceipt: "Download admission receipt",
  downloadPreview: "Download review details",
  preview: "Preview transactions",
  previewHelp:
    "Check the suggested column names against your file. File format can be adjusted below. Every row is validated in the preview; nothing is imported yet.",
  choose: "Choose…",
  delimiter: "Column delimiter",
  comma: "Comma",
  semicolon: "Semicolon",
  tab: "Tab",
  lineEnding: "Record line endings",
  lf: "LF",
  crlf: "CRLF",
  dateColumn: "Date column",
  descriptionColumn: "Description column",
  amountColumn: "Amount column",
  providerIdColumn: "Transaction reference column (optional)",
  dateFormat: "Date format",
  decimalSeparator: "Decimal separator",
  dot: "Dot",
  sign: "Positive amounts mean",
  inflow_positive: "Positive means inflow",
  outflow_positive: "Positive means outflow",
  accountId: "Account",
  currency: "Declared currency",
  currencyScale: "Declared currency scale",
  startsOn: "Statement starts",
  endsOn: "Statement ends",
  openingMinor: "Declared opening balance (minor units)",
  closingMinor: "Declared closing balance (minor units)",
  declaredComplete: "This file covers the entire statement period",
  basis: "Coverage note",
  controlsHelp:
    "Enter the opening and closing balances printed on the statement. Confirm completeness only if the file covers the entire interval.",
  previewId: "Retained preview identity",
  openPreview: "Open selected preview",
  ready: "Ready for review. Import requires your approval.",
  blocked: "Blocked. No observations can be admitted from this preview.",
  stale: "Dependencies changed. Create and review a new preview.",
  unknown: "Current state is unavailable. Refresh before acting.",
  bom: "UTF-8 BOM present",
  structuralComplete: "All CSV records parsed",
  yes: "Yes",
  no: "No",
  diagnostics: "Diagnostics",
  code: "Code",
  record: "CSV record",
  line: "Physical line",
  bytes: "Byte range (start inclusive, end exclusive)",
  fields: "Retained field values",
  rows: "Transactions",
  date: "Date",
  description: "Description",
  amount: "Signed minor units",
  provider: "Reference",
  movement: "Movement",
  mapping: "Reviewed mapping and declarations",
  edit: "Edit mapping",
  digest: "Preview digest",
  operator:
    "Only an operator can approve and admit an interpretation. The approving operator must perform admission.",
  review:
    "I reviewed the original bytes, every record, unused columns, mapping, sign, dates, currency, controls and coverage declaration.",
  rationale: "Review rationale",
  approve: "Approve this exact preview",
  expires: "Approval expires",
  admit: "Import approved transactions",
  admitted: "Statement imported. Its transactions are ready for reconciliation.",
  receipt: "Admission receipt",
  statement: "Bank statement",
  different: "This occurrence was admitted through another retained preview.",
  plainUnavailable:
    "The original cannot be displayed as UTF-8 text. Download its exact bytes and inspect the retained diagnostics.",
  reason: "Message",
  previous: "Previous rows",
  range: "Row page",
  approvalHelp:
    "Approval expires after one hour. If admission outcome is uncertain, retry without changing the input, or refresh this source to recover its durable receipt.",
};

const sv = {
  title: "Bevara källdokument",
  scope:
    "Endast observerade källor. Detta är inte en förteckning över obligatoriska källor, bokföringsklassificering eller bevis på fullständigt företagsunderlag. Ingen bokföring eller automatisk matchning sker.",
  retainedOnly:
    "Originalet har bevarats. Bank-CSV-tolkning stöder CSV-filer upp till 64 KiB. Övriga dokument kan hämtas som original.",
  limits:
    "Originaldokument: högst 5 MiB med konfigurerad arkivlagring. CSV-profil: UTF-8 bank_csv_utf8_v1. Högst 64 KiB, 200 datarader, 32 kolumner och 4000 byte per fält. Import av observationer stöder för närvarande endast synthetic-core-v1.",
  retain: "Bevara originalfil",
  file: "Originalfil",
  sourceSystem: "Källsystem",
  sourceAccountId: "Källkontots identitet",
  occurrenceKey: "Stabil identitet för källförekomsten",
  sourceRevision: "Källans revisionsidentitet",
  identityHelp:
    "Återanvänd förekomst- och revisionsidentiteter vid nytt försök för samma hämtning. Olika förekomster kan ha samma byte. Använd inte innehållshashen som förekomstidentitet.",
  inventory: "Bevarade förekomster",
  refresh: "Uppdatera",
  first: "Första sidan",
  next: "Nästa sida",
  load: "Öppna bevarad källa",
  empty: "Inga bevarade källförekomster på denna sida. Det betyder inte att inga källor behövs.",
  invalid: "Kontrollera obligatoriska fält och tillåtna värden.",
  invalidFile: "Välj en fil med högst 5 MiB och minst 1 byte.",
  readFailure: "Filen kunde inte läsas. Ingen ny fil skickades.",
  original: "Visa originalfil",
  download: "Hämta originalfil",
  downloadReceipt: "Hämta importkvitto",
  downloadPreview: "Hämta oföränderlig förhandsgranskning",
  preview: "Förhandsgranska transaktioner",
  previewHelp:
    "Kontrollera föreslagna kolumner mot filen. Filformatet kan ändras nedan. Alla rader kontrolleras i förhandsgranskningen; inget importeras ännu.",
  choose: "Välj…",
  delimiter: "Kolumnavgränsare",
  comma: "Komma",
  semicolon: "Semikolon",
  tab: "Tabb",
  lineEnding: "Radslut",
  lf: "LF",
  crlf: "CRLF",
  dateColumn: "Datumkolumn",
  descriptionColumn: "Beskrivningskolumn",
  amountColumn: "Beloppskolumn",
  providerIdColumn: "Referenskolumn (valfritt)",
  dateFormat: "Datumformat",
  decimalSeparator: "Decimalavgränsare",
  dot: "Punkt",
  sign: "Positiva belopp betyder",
  inflow_positive: "Positivt betyder inflöde",
  outflow_positive: "Positivt betyder utflöde",
  accountId: "Konto",
  currency: "Angiven valuta",
  currencyScale: "Angivet antal valutadecimaler",
  startsOn: "Kontoutdrag från",
  endsOn: "Kontoutdrag till",
  openingMinor: "Angivet ingående saldo (minsta valutaenhet)",
  closingMinor: "Angivet utgående saldo (minsta valutaenhet)",
  declaredComplete: "Filen omfattar hela kontoutdragsperioden",
  basis: "Anteckning om täckning",
  controlsHelp:
    "Ange oberoende saldon, inte härledda saldon. En omarkerad fullständighetsförklaring betyder ofullständigt, inte okänt eller noll. Två valutadecimaler innebär 100 minsta enheter per valutaenhet.",
  previewId: "Förhandsgranskningens identitet",
  openPreview: "Öppna vald förhandsgranskning",
  ready: "Inga blockerande fel. Operatörsgranskning krävs fortfarande.",
  blocked: "Blockerad. Inga observationer kan importeras från denna förhandsgranskning.",
  stale: "Beroenden har ändrats. Skapa och granska en ny förhandsgranskning.",
  unknown: "Aktuellt tillstånd är inte tillgängligt. Uppdatera innan du fortsätter.",
  bom: "UTF-8-BOM finns",
  structuralComplete: "Alla CSV-poster har tolkats",
  yes: "Ja",
  no: "Nej",
  diagnostics: "Diagnostik",
  code: "Kod",
  record: "CSV-post",
  line: "Fysisk rad",
  bytes: "Byteintervall (från inklusive, till exklusive)",
  fields: "Bevarade fältvärden",
  rows: "Normaliserade observationer",
  date: "Datum",
  description: "Beskrivning",
  amount: "Minsta valutaenheter med tecken",
  provider: "Leverantörens radidentitet",
  movement: "Summa giltiga rörelser (minsta valutaenhet)",
  mapping: "Granskad mappning och deklarationer",
  edit: "Använd mappningen för ny förhandsgranskning",
  digest: "Förhandsgranskningens hash",
  operator:
    "Endast en operatör kan godkänna och importera en tolkning. Samma operatör måste godkänna och importera.",
  review:
    "Jag har granskat originalbyte, varje post, oanvända kolumner, mappning, tecken, datum, valuta, kontrollsaldon och täckningsförklaringen.",
  rationale: "Motivering till granskningen",
  approve: "Godkänn exakt denna förhandsgranskning",
  expires: "Godkännandet upphör",
  admit: "Importera granskade observationer",
  admitted: "Observationer importerade. Inga bokföringsrader skapades eller matchades.",
  receipt: "Importkvitto",
  statement: "Bankutdrag",
  different: "Förekomsten importerades via en annan bevarad förhandsgranskning.",
  plainUnavailable:
    "Originalet kan inte visas som UTF-8-text. Hämta originalbyte och granska bevarad diagnostik.",
  reason: "Meddelande",
  previous: "Föregående rader",
  range: "Radsida",
  approvalHelp:
    "Godkännandet gäller en timme. Vid osäkert importresultat: försök igen utan att ändra indata, eller uppdatera källan för att hämta det beständiga kvittot.",
} satisfies Record<keyof typeof en, string>;

export function intakeCopy(locale: Locale) {
  return locale === "sv" ? sv : en;
}
