import type { Locale } from "@/paraglide/runtime";

export function allocationReversalCopy(locale: Locale) {
  return locale === "sv"
    ? {
        title: "Ångra betalningsfördelning",
        boundary:
          "Frigör hela fördelningen mellan en bokförd betalning och fakturor. Originalen sparas. Ingen bokföring, kreditfaktura, återbetalning eller betalningsorder skapas.",
        history: "Sparade granskningar",
        live: "Listan visar sparade granskningar, inte ett fullständigt underlagsregister. Uppdatera första sidan för nya poster.",
        receipt: "Fördelningskvitto",
        review: "Granska hela fördelningen",
        plan: "Öppna granskning",
        prepare: "Förbered granskning",
        reason: "Orsak",
        refresh: "Uppdatera",
        created: "Skapad",
        state: "Status",
        active: "Fördelningen är aktiv",
        reversed: "Hela fördelningen har frigjorts",
        pending: "Inte genomförd",
        ready: "Granskningen är aktuell",
        stale: "Underlaget har ändrats. Förbered en ny granskning.",
        unknown: "Aktuell status måste hämtas innan du fortsätter.",
        digest: "Granskningens kontrollsumma",
        original: "Ursprunglig plan och kvitto",
        evidence: "Betalningens underlag",
        invoices: "Fakturor och frigjort belopp",
        invoice: "Faktura",
        allocated: "Fördelat före",
        released: "Frigörs",
        outstanding: "Utestående före",
        after: "Utestående efter",
        payment: "Bokförd betalning",
        remaining: "Tillgängligt före",
        remainingAfter: "Tillgängligt efter",
        units: "Belopp i minsta valutaenhet",
        periods: "Berörda öppna perioder",
        versions: "Periodversioner",
        approve: "Godkänn hela frigörandet",
        execute: "Frigör hela fördelningen",
        revoke: "Återkalla godkännande",
        revokeReason: "Orsak till återkallande",
        acknowledge:
          "Jag har granskat alla fakturor, belopp, perioder och underlag. Jag godkänner att hela fördelningen frigörs utan att bokföringen ändras.",
        operator: "En behörig operatör måste godkänna granskningen.",
        expires: "Godkännandet gäller till",
        approvals: "Godkännandehistorik",
        execution: "Kvitto för genomfört frigörande",
        impact:
          "Öppna fakturor och betalningsutrymme räknas om. Tidigare planer, registerrapporter och periodgranskningar kan bli inaktuella. Original och tidigare rapporter ändras inte. Berörda låsta perioder måste öppnas separat.",
        report: "Kontrollera registerrapport",
        reportCurrent:
          "Fördelningsunderlaget matchar rapporten. Andra beroenden och fullständighet har inte kontrollerats.",
        reportStale:
          "Rapportens fördelningsunderlag är inaktuellt. Skapa en ny registerrapport. Det sparade originalet är oförändrat.",
        empty: "Inga sparade granskningar på den här sidan.",
        facts: "Sparade uppgifter",
        download: "Ladda ner granskning och kvitto",
      }
    : {
        title: "Unallocate a payment",
        boundary:
          "Release one whole allocation between a posted payment and its invoices. Keep every original. No ledger reversal, credit note, refund or payment instruction is created.",
        history: "Retained reviews",
        live: "These are live review pages, not a complete source inventory. Refresh the first page to find new records.",
        receipt: "Allocation receipt",
        review: "Review the whole allocation",
        plan: "Open review",
        prepare: "Prepare review",
        reason: "Reason",
        refresh: "Refresh",
        created: "Created",
        state: "Status",
        active: "Allocation is active",
        reversed: "Whole allocation released",
        pending: "Not executed",
        ready: "Review dependencies are current",
        stale: "The basis changed. Prepare a new review.",
        unknown: "Fetch current status before continuing.",
        digest: "Review digest",
        original: "Original plan and receipt",
        evidence: "Payment evidence",
        invoices: "Invoices and released amounts",
        invoice: "Invoice",
        allocated: "Allocated before",
        released: "To release",
        outstanding: "Outstanding before",
        after: "Outstanding after",
        payment: "Posted payment",
        remaining: "Available before",
        remainingAfter: "Available after",
        units: "Amounts in minor units",
        periods: "Affected open periods",
        versions: "Period versions",
        approve: "Approve whole release",
        execute: "Release whole allocation",
        revoke: "Revoke approval",
        revokeReason: "Revocation reason",
        acknowledge:
          "I reviewed every invoice, amount, period and evidence reference. I approve releasing the whole allocation without changing the ledger.",
        operator: "An authorized operator must approve this review.",
        expires: "Approval expires",
        approvals: "Approval history",
        execution: "Committed release receipt",
        impact:
          "Open items and payment capacity will change. Earlier plans, register reports and closing reviews may become stale. Original records and past reports stay unchanged. Locked affected periods require a separate reopen.",
        report: "Check register report",
        reportCurrent:
          "Allocation dependencies match this report. Other dependencies and completeness were not checked.",
        reportStale:
          "The report allocation basis is stale. Create a new register report. The retained original is unchanged.",
        empty: "No retained reviews on this page.",
        facts: "Retained facts",
        download: "Download review and receipt",
      };
}
