import type { Locale } from "@/paraglide/runtime";

const en = {
  registerReports: "Saved register snapshots",
  captureRegister: "Save register snapshot",
  asOfDate: "Economic as-of date",
  capturedAt: "Captured at",
  registerBasis:
    "Synthetic report of currently declared control accounts. Uses facts known at capture and posting dates through the as-of date, not what was known on that date. Due dates use the metadata revision saved at capture. Source completeness is not established.",
  registerLimits:
    "At most 100 declared accounts, 2,000 combined invoices, allocation legs and ledger lines, and 2 MiB per report. Larger scopes are rejected, not truncated. No posting or payment is created.",
  registerListNote:
    "Saved reports in capture order, 20 per page at a fixed inventory cutoff. First page keeps that cutoff. Refresh starts a new inventory that includes later reports.",
  registerInventoryCount: "Reports in this inventory",
  registerInventoryCutoff: "Inventory ordinal cutoff",
  registerBalanced:
    "Registered amounts agree with declared control accounts. Source completeness is not established.",
  registerDifferences:
    "Unexplained control-account entries remain. Inspect each contribution, even when differences net to zero.",
  registerNoAccounts:
    "No commerce control accounts have been declared. This is not evidence that no invoices exist.",
  registerControls: "Control-account comparison",
  registerLedger: "Retained ledger contributions",
  registerInvoices: "Invoice ageing at capture",
  registerAllocations: "Retained allocation legs",
  registerAgeing: "Outstanding amounts by overdue age",
  registerDownload: "Download full snapshot JSON",
  registerPage:
    "Saved snapshot rows, 50 per page. The JSON download always contains the full snapshot.",
  previous: "Previous page",
  ledgerSequence: "Ledger cutoff sequence",
  ledgerAmount: "Ledger balance (direction-positive)",
  registerDifference: "Ledger minus register",
  unexplainedLines: "Unexplained lines",
  unexplainedAmount: "Unexplained minor units",
  registerEffect: "Register effect minor units",
  registerSign:
    "Customer balances are debit-positive. Supplier balances are credit-positive. Unexplained settlement-side entries are not proof of payment. All amounts are exact minor units.",
  notDue: "Not overdue",
  days1To30: "1–30 days",
  days31To60: "31–60 days",
  days61To90: "61–90 days",
  over90: "Over 90 days",
  daysOverdue: "Days overdue",
  allocationReceipt: "Allocation receipt / leg",
  postingDate: "Posting date",
  title: "Invoice drafts, register and allocations",
  limit:
    "Commercial drafts and the synthetic posted-invoice register are separate. Saving a draft does not register recognition. Nothing here issues invoices, posts accounting or initiates payments. VAT and legal identity are not verified.",
  parties: "Counterparties",
  invoices: "Registered invoices",
  allocations: "Payment allocations",
  createParty: "Register counterparty",
  reviseParty: "Append name revision",
  registerInvoice: "Register existing recognition",
  reviseInvoice: "Append invoice metadata revision",
  externalKey: "Stable source identity",
  role: "Role",
  customer: "Customer",
  supplier: "Supplier",
  both: "Customer and supplier",
  name: "Name",
  evidenceId: "Retained evidence ID",
  reason: "Reason",
  description: "Description",
  id: "Saved record ID",
  open: "Open saved record",
  refresh: "Refresh",
  first: "First page",
  next: "Next page",
  pageNote:
    "Live page, at most 50 records. Not a complete inventory or control-account reconciliation.",
  empty: "No records on this page.",
  revision: "Revision",
  historical: "Historical revision (read-only)",
  current: "Read current revision",
  readRevision: "Read revision",
  partyId: "Counterparty ID",
  partyRevision: "Reviewed counterparty revision",
  document: "Source invoice number",
  issued: "Source issue date",
  due: "Due date",
  amount: "Amount in exact minor units",
  account: "Declared control account ID",
  voucher: "Posted voucher ID",
  line: "Posted control-line ID",
  recognitionHelp:
    "Use an existing exact customer debit or supplier credit control line and its original retained evidence. Financial identity and amount cannot be changed here.",
  units: "Amounts are minor-unit strings, never decimal currency input. Currency:",
  scale: "Currency scale",
  outstanding: "Outstanding minor units",
  recordedAllocated: "Recorded allocated minor units",
  blockedAmount: "Unavailable: inspect blockers",
  openStatus: "Open",
  partialStatus: "Partially allocated",
  allocatedStatus: "Fully allocated in this register",
  blockedStatus: "Blocked",
  status: "Register status",
  history: "Immutable invoice history",
  facts: "Retained details and references",
  evidence: "Inspect retained evidence",
  capacity: "Inspect posted payment capacity",
  capacityHelp:
    "Use an opposite-side posted settlement control line, not a bank row. Bank matching does not allocate invoices.",
  remaining: "Unallocated payment minor units",
  prepare: "Prepare allocation proposal",
  invoiceId: "Invoice ID",
  addLeg: "Add invoice leg",
  removeLeg: "Remove invoice leg",
  legsHelp:
    "Allocate to 1–50 invoices for the same counterpart and control account. No payment is initiated.",
  review: "Review exact allocation",
  planId: "Saved allocation plan ID",
  digest: "Sealed digest",
  before: "Outstanding before",
  after: "Outstanding after",
  total: "Total allocation minor units",
  fresh: "Reviewed dependencies are current. The server checks them again before applying.",
  stale: "Dependencies changed. Prepare a new proposal; do not reuse this review.",
  approve: "Approve exact allocation",
  apply: "Apply approved allocation",
  operatorOnly: "An operator must approve. Agent credentials cannot create approval.",
  approval: "Operator approval",
  expired: "Approval expired. Obtain a new operator approval.",
  applied: "Allocation recorded. No new posting or payment was created.",
  ack: "I reviewed the exact digest, evidence, all invoice legs and payment remainder. This approval is only for allocation.",
  key: "Retry key (save with the request)",
  generateKey: "Generate new key",
  keyHelp:
    "No automatic persistence. Before sending, save the exact form values, revision and retry key. Reloading or leaving this view can lose an unsaved request. The JSON export is available only after sending. To recover, use the same book, actor, values and key, or open the saved record. Never replace a key because a response was lost.",
  retry: "Retry exact request",
  newCommand: "Start a new command",
  download: "Save request and outcome JSON",
  request: "Captured request and outcome",
  saved: "Request completed. Retain the record ID and receipt.",
  invalid: "Check the required fields, identifiers, dates and exact minor-unit strings.",
  waiting:
    "Refresh this record before another change. Cached or failed reads do not grant authority.",
  newProposal:
    "Prepare a new proposal after a stale or rejected review. An unchanged retry only recovers the same command.",
  sourceNote:
    "Retain source evidence through the existing evidence workflow first. These forms only reference retained evidence.",
};

const sv = {
  registerReports: "Sparade registerrapporter",
  captureRegister: "Spara registerrapport",
  asOfDate: "Ekonomiskt avstämningsdatum",
  capturedAt: "Sparad tidpunkt",
  registerBasis:
    "Syntetisk rapport över nu deklarerade kontrollkonton. Använder uppgifter kända när rapporten sparas och bokföringsdatum till och med avstämningsdatumet, inte vad som var känt då. Förfallodatum hämtas från den fakturarevision som sparas i rapporten. Underlagens fullständighet är inte fastställd.",
  registerLimits:
    "Högst 100 deklarerade konton, sammanlagt 2 000 fakturor, fördelningsrader och huvudboksrader samt 2 MiB per rapport. Större urval avvisas, inte trunkeras. Ingen bokföring eller betalning skapas.",
  registerListNote:
    "Sparade rapporter i sparordning, 20 per sida med en fast inventeringsgräns. Första sidan behåller gränsen. Uppdatera startar en ny inventering med senare rapporter.",
  registerInventoryCount: "Rapporter i denna inventering",
  registerInventoryCutoff: "Inventeringens ordningsgräns",
  registerBalanced:
    "Registrerade belopp stämmer med deklarerade kontrollkonton. Underlagens fullständighet är inte fastställd.",
  registerDifferences:
    "Oförklarade kontrollrader återstår. Granska varje bidrag även om differenserna tar ut varandra.",
  registerNoAccounts:
    "Inga kontrollkonton för fakturor har deklarerats. Det bevisar inte att fakturor saknas.",
  registerControls: "Jämförelse med kontrollkonton",
  registerLedger: "Bevarade huvudboksbidrag",
  registerInvoices: "Fakturornas ålder i rapporten",
  registerAllocations: "Bevarade fördelningsrader",
  registerAgeing: "Utestående belopp efter förfallen tid",
  registerDownload: "Ladda ner hela rapporten som JSON",
  registerPage: "Sparade rapportrader, 50 per sida. JSON-filen innehåller alltid hela rapporten.",
  previous: "Föregående sida",
  ledgerSequence: "Huvudbokens avgränsningssekvens",
  ledgerAmount: "Huvudbokssaldo (positivt i kontots riktning)",
  registerDifference: "Huvudbok minus register",
  unexplainedLines: "Oförklarade rader",
  unexplainedAmount: "Oförklarade minor units",
  registerEffect: "Registereffekt i minor units",
  registerSign:
    "Kundsaldo är positivt i debet. Leverantörssaldo är positivt i kredit. Oförklarade rader på regleringssidan bevisar inte betalning. Alla belopp är exakta minor units.",
  notDue: "Inte förfallen",
  days1To30: "1–30 dagar",
  days31To60: "31–60 dagar",
  days61To90: "61–90 dagar",
  over90: "Över 90 dagar",
  daysOverdue: "Förfallna dagar",
  allocationReceipt: "Fördelningskvitto / rad",
  postingDate: "Bokföringsdatum",
  title: "Fakturautkast, register och fördelningar",
  limit:
    "Kommersiella utkast och det syntetiska registret över bokförda fakturor är separata. Ett sparat utkast registrerar ingen bokföring. Inget här utfärdar fakturor, bokför eller initierar betalningar. Moms och juridisk identitet är inte verifierade.",
  parties: "Motparter",
  invoices: "Registrerade fakturor",
  allocations: "Betalningsfördelningar",
  createParty: "Registrera motpart",
  reviseParty: "Lägg till namnrevision",
  registerInvoice: "Registrera befintlig bokföring",
  reviseInvoice: "Lägg till fakturarevision",
  externalKey: "Stabil källidentitet",
  role: "Roll",
  customer: "Kund",
  supplier: "Leverantör",
  both: "Kund och leverantör",
  name: "Namn",
  evidenceId: "ID för bevarat underlag",
  reason: "Orsak",
  description: "Beskrivning",
  id: "Sparat post-ID",
  open: "Öppna sparad post",
  refresh: "Uppdatera",
  first: "Första sidan",
  next: "Nästa sida",
  pageNote:
    "Aktuell sida, högst 50 poster. Inte en fullständig inventering eller avstämning av kontrollkonto.",
  empty: "Inga poster på den här sidan.",
  revision: "Revision",
  historical: "Historisk revision (skrivskyddad)",
  current: "Läs aktuell revision",
  readRevision: "Läs revision",
  partyId: "Motparts-ID",
  partyRevision: "Granskad motpartsrevision",
  document: "Ursprungligt fakturanummer",
  issued: "Ursprungligt fakturadatum",
  due: "Förfallodatum",
  amount: "Belopp i exakta minor units",
  account: "Deklarerat kontrollkonto-ID",
  voucher: "Bokfört verifikations-ID",
  line: "ID för bokförd kontrollrad",
  recognitionHelp:
    "Använd en befintlig exakt kontrollrad: kundfordran i debet eller leverantörsskuld i kredit, med ursprungligt bevarat underlag. Ekonomisk identitet och belopp kan inte ändras här.",
  units: "Belopp anges som heltalssträngar i minor units, inte som decimala valutabelopp. Valuta:",
  scale: "Valutaskala",
  outstanding: "Återstående minor units",
  recordedAllocated: "Registrerade fördelade minor units",
  blockedAmount: "Ej tillgängligt: granska hinder",
  openStatus: "Öppen",
  partialStatus: "Delvis fördelad",
  allocatedStatus: "Helt fördelad i detta register",
  blockedStatus: "Blockerad",
  status: "Registerstatus",
  history: "Oföränderlig fakturahistorik",
  facts: "Bevarade uppgifter och referenser",
  evidence: "Granska bevarat underlag",
  capacity: "Granska bokförd betalningskapacitet",
  capacityHelp:
    "Använd en bokförd kontrollrad för reglering på motsatt sida, inte en bankrad. Bankmatchning fördelar inte fakturor.",
  remaining: "Ofördelade minor units på betalningen",
  prepare: "Förbered fördelningsförslag",
  invoiceId: "Faktura-ID",
  addLeg: "Lägg till fakturarad",
  removeLeg: "Ta bort fakturarad",
  legsHelp:
    "Fördela på 1–50 fakturor för samma motpart och kontrollkonto. Ingen betalning initieras.",
  review: "Granska exakt fördelning",
  planId: "Sparat fördelningsplans-ID",
  digest: "Förseglat digest",
  before: "Återstående före",
  after: "Återstående efter",
  total: "Totala fördelade minor units",
  fresh: "Granskade beroenden är aktuella. Servern kontrollerar dem igen före verkställande.",
  stale: "Beroenden har ändrats. Förbered ett nytt förslag; återanvänd inte denna granskning.",
  approve: "Godkänn exakt fördelning",
  apply: "Verkställ godkänd fördelning",
  operatorOnly: "En operatör måste godkänna. Agentbehörighet kan inte skapa godkännande.",
  approval: "Operatörsgodkännande",
  expired: "Godkännandet har löpt ut. Begär ett nytt operatörsgodkännande.",
  applied: "Fördelningen har registrerats. Ingen ny bokföring eller betalning skapades.",
  ack: "Jag har granskat exakt digest, underlag, alla fakturarader och betalningens återstående belopp. Godkännandet gäller endast fördelning.",
  key: "Återförsöksnyckel (spara med begäran)",
  generateKey: "Skapa ny nyckel",
  keyHelp:
    "Ingen automatisk lagring. Spara exakta formulärvärden, revision och återförsöksnyckel innan du skickar. Omladdning eller byte av vy kan förlora en osparad begäran. JSON-exporten är tillgänglig först efter att du skickat. Återhämta med samma bok, aktör, värden och nyckel eller öppna sparad post. Byt aldrig nyckel för att ett svar saknas.",
  retry: "Försök igen med exakt begäran",
  newCommand: "Starta en ny åtgärd",
  download: "Spara begäran och resultat som JSON",
  request: "Sparad begäran och resultat",
  saved: "Begäran slutfördes. Behåll post-ID och kvitto.",
  invalid: "Kontrollera obligatoriska fält, ID, datum och exakta minor-unit-strängar.",
  waiting:
    "Uppdatera posten före nästa ändring. Cachade eller misslyckade läsningar ger ingen behörighet.",
  newProposal:
    "Förbered ett nytt förslag efter en inaktuell eller nekad granskning. Ett oförändrat återförsök återhämtar endast samma åtgärd.",
  sourceNote:
    "Bevara källunderlag via det befintliga underlagsflödet först. Dessa formulär refererar endast till bevarat underlag.",
} satisfies Record<keyof typeof en, string>;

export function commerceCopy(locale: Locale) {
  return locale === "sv" ? sv : en;
}
