import type { Locale } from "@/paraglide/runtime";

const en = {
  title: "Cancel synthetic invoice",
  boundary: "Whole native synthetic invoices only. Cancellation reverses the exact original recognition. It does not issue a legal credit, refund money, unallocate payments or deliver a document.",
  retained: "The original issue, draft, register record, document artifacts and SYN number remain historical and immutable. The draft does not reopen and the number cannot be reused.",
  requirements: "Explicitly unallocate every active payment first. Both recognition and cancellation periods must be open. Bank, owner, schedule and correction conflicts block cancellation.",
  active: "No cancellation is recorded for this synthetic issue.",
  cancelled: "Synthetic invoice cancelled. Recognition was reversed once. No refund or legal credit was issued.",
  unknown: "Refresh to confirm current cancellation and approval state.",
  refresh: "Refresh cancellation status",
  prepare: "Prepare whole cancellation review",
  period: "Cancellation accounting period",
  date: "Cancellation posting date",
  reason: "Reason for cancellation",
  acknowledge: "I understand this cancels only a synthetic invoice and reverses its entire recognition. It does not create a legal credit, refund or delivery.",
  history: "Saved cancellation reviews",
  empty: "No cancellation reviews have been prepared.",
  review: "Cancellation review",
  recover: "Open saved cancellation review",
  original: "Original synthetic issue",
  invoice: "Retained invoice basis",
  posting: "Exact reversal journal",
  evidence: "Original retained evidence",
  account: "Account",
  debit: "Debit minor units",
  credit: "Credit minor units",
  ready: "The reviewed dependencies remain current.",
  stale: "The review is stale or blocked. Inspect the live issue, then prepare a new review. Nothing was cancelled by this review.",
  digest: "Review digest",
  approve: "Approve this whole synthetic cancellation",
  execute: "Cancel synthetic invoice and reverse recognition",
  authority: "Approval lasts one hour. The same current operator must execute it. It can be revoked before execution.",
  expires: "Approval expires",
  operator: "Only a current book operator can prepare, approve, revoke or execute cancellation.",
  revoke: "Revoke cancellation approval",
  revokeReason: "Reason for revoking approval",
  approvals: "Retained approval and revocation history",
  receipt: "Immutable cancellation receipt",
  journal: "Retained reversal plan",
};
const sv: typeof en = {
  title: "Makulera syntetisk faktura",
  boundary: "Endast hela inbyggda syntetiska fakturor. Makuleringen återför exakt den ursprungliga bokföringen. Den skapar ingen juridisk kreditfaktura, återbetalar inga pengar, tar inte bort betalningsfördelningar och skickar inget dokument.",
  retained: "Ursprungligt utfärdande, utkast, registerpost, dokument och SYN-nummer bevaras oförändrade som historik. Utkastet öppnas inte igen och numret kan inte återanvändas.",
  requirements: "Ångra först alla aktiva betalningsfördelningar uttryckligen. Både ursprungsperioden och makuleringsperioden måste vara öppna. Kopplingar till bank, ägare, periodisering eller rättelser kan stoppa makuleringen.",
  active: "Ingen makulering finns för denna syntetiska faktura.",
  cancelled: "Syntetisk faktura makulerad. Bokföringen har återförts en gång. Ingen återbetalning eller juridisk kreditfaktura har skapats.",
  unknown: "Uppdatera för att bekräfta aktuell makulering och godkännande.",
  refresh: "Uppdatera makuleringsstatus",
  prepare: "Förbered granskning av hel makulering",
  period: "Bokföringsperiod för makulering",
  date: "Bokföringsdatum för makulering",
  reason: "Skäl till makulering",
  acknowledge: "Jag förstår att detta endast makulerar en syntetisk faktura och återför hela dess bokföring. Ingen juridisk kreditfaktura, återbetalning eller leverans skapas.",
  history: "Sparade makuleringsgranskningar",
  empty: "Inga makuleringsgranskningar har förberetts.",
  review: "Makuleringsgranskning",
  recover: "Öppna sparad makuleringsgranskning",
  original: "Ursprungligt syntetiskt utfärdande",
  invoice: "Bevarat fakturaunderlag",
  posting: "Exakt återföringsverifikation",
  evidence: "Ursprungligt bevarat underlag",
  account: "Konto",
  debit: "Debet i minsta valutaenhet",
  credit: "Kredit i minsta valutaenhet",
  ready: "De granskade beroendena är fortfarande aktuella.",
  stale: "Granskningen är inaktuell eller blockerad. Granska fakturans aktuella status och förbered en ny granskning. Denna granskning har inte makulerat något.",
  digest: "Granskningens kontrollsumma",
  approve: "Godkänn hela denna syntetiska makulering",
  execute: "Makulera syntetisk faktura och återför bokföringen",
  authority: "Godkännandet gäller i en timme. Samma behöriga operatör måste utföra makuleringen. Godkännandet kan återkallas före utförande.",
  expires: "Godkännandet löper ut",
  operator: "Endast en aktuell operatör för boken får förbereda, godkänna, återkalla eller utföra makulering.",
  revoke: "Återkalla godkännande av makulering",
  revokeReason: "Skäl till återkallat godkännande",
  approvals: "Bevarad historik över godkännanden och återkallelser",
  receipt: "Oföränderligt makuleringskvitto",
  journal: "Bevarad återföringsplan",
};
export const invoiceCancellationCopy = (locale: Locale) => locale === "sv" ? sv : en;
