import type { Locale } from "@/paraglide/runtime";

const en = {
  title: "Synthetic invoice issue",
  boundary:
    "Synthetic books only. This review can issue an internal SYN document, post the two accounts you choose and register a customer receivable in one transaction. It does not issue a legal invoice, determine VAT or send a document.",
  requirements:
    "Use a complete customer draft with matching source totals and evidenced zero asserted tax. Both accounts are your explicit synthetic mapping. No real tax treatment or account classification is inferred.",
  openDraft: "Open draft for issue review",
  openReview: "Open saved issue review",
  prepare: "Prepare issue and posting review",
  control: "Receivables account (debit)",
  credit: "Revenue account (credit)",
  period: "Accounting period",
  series: "Voucher series",
  reason: "Reason for this issue and account choice",
  acknowledge: "I understand this is synthetic-only, not a legal invoice or VAT determination.",
  snapshot:
    "This form uses the displayed retained draft revision. Refreshing remote data does not replace it. If facts change, reopen the draft and prepare a new review.",
  history: "Saved issue reviews for this draft",
  empty: "No issue reviews have been prepared for this draft.",
  review: "Exact issue and posting review",
  draft: "Draft",
  revision: "Revision",
  titleColumn: "Title",
  customer: "Asserted customer",
  seller: "Asserted seller",
  total: "Gross amount in minor units",
  currency: "Currency",
  scale: "Currency scale",
  digest: "Review digest",
  internal: "Internal synthetic document",
  id: "Record ID",
  created: "Created at",
  approve: "Approve synthetic issue and these journal lines",
  execute: "Issue synthetic document and post once",
  approval: "Retained human approval",
  approvalNote:
    "Approval lasts one hour. Only the same current operator can execute it. Approval alone does not issue or post.",
  expires: "Approval expires at",
  operator: "Approving operator",
  blocked: "Execution blockers",
  unavailable:
    "There is no usable approval. Review the current facts and approve before executing.",
  success:
    "Synthetic document issued and customer recognition posted. Nothing was delivered. The SYN number is not a legal invoice number.",
  posting: "Exact proposed journal lines",
  account: "Account ID",
  debit: "Debit minor units",
  creditAmount: "Credit minor units",
  description: "Description",
  postingDate: "Posting date",
  dueDate: "Due date",
  details: "Complete retained review and receipts",
  legal: "Real-company limitations remain",
  draftFacts: "Frozen commercial content and exact line calculations",
  commercialLines: "Frozen commercial lines",
  quantity: "Quantity",
  base: "Base minor units",
  discount: "Discount minor units",
  charge: "Charge minor units",
  tax: "Asserted tax minor units",
  sourceGross: "Source gross minor units",
  evidence: "Retained draft evidence",
  receipt: "Posting receipt",
  register: "Customer register invoice ID",
  refresh: "Refresh saved state",
  download: "Download exact review and receipt JSON",
  recovery:
    "Use the saved draft and review IDs to recover after reload. Download the request and retry key before leaving an uncertain command. Do not start a new command to guess its outcome.",
  issued: "Issued",
  pending: "Not issued",
  rules:
    "Frozen draft blockers describe the original draft boundary. This separate synthetic profile does not remove its legal identity, legal numbering or tax limitations.",
};
const sv: typeof en = {
  title: "Syntetiskt fakturautfärdande",
  boundary:
    "Endast syntetiska böcker. Granskningen kan skapa ett internt SYN-dokument, bokföra de två konton du väljer och registrera en kundfordran i samma transaktion. Den utfärdar ingen juridisk faktura, bedömer inte moms och skickar inget dokument.",
  requirements:
    "Använd ett komplett kundutkast med avstämda källbelopp och styrkt skattebelopp noll. Båda kontona är ditt uttryckliga syntetiska val. Ingen verklig skattebehandling eller kontoklassificering antas.",
  openDraft: "Öppna utkast för granskning",
  openReview: "Öppna sparad utfärdandegranskning",
  prepare: "Förbered utfärdande och bokföring",
  control: "Kontrollkonto för kundfordran, debet",
  credit: "Kontots ID för kredit",
  period: "Bokföringsperiod",
  series: "Verifikationsserie",
  reason: "Skäl för utfärdandet och kontovalet",
  acknowledge:
    "Jag förstår att detta endast är syntetiskt, inte en juridisk faktura eller momsbedömning.",
  snapshot:
    "Formuläret använder den visade sparade utkastrevisionen. Uppdatering av serverdata ersätter den inte. Om uppgifterna ändras, öppna utkastet igen och förbered en ny granskning.",
  history: "Sparade utfärdandegranskningar för utkastet",
  empty: "Inga utfärdandegranskningar har förberetts för utkastet.",
  review: "Exakt utfärdande- och bokföringsgranskning",
  draft: "Utkast",
  revision: "Revision",
  titleColumn: "Titel",
  customer: "Kund enligt källan",
  seller: "Säljare enligt källan",
  total: "Bruttobelopp i minsta valutaenhet",
  currency: "Valuta",
  scale: "Valutans decimaler",
  digest: "Granskningens kontrollsumma",
  internal: "Internt syntetiskt dokument",
  id: "Postens ID",
  created: "Skapad",
  approve: "Godkänn syntetiskt utfärdande och dessa bokföringsrader",
  execute: "Utfärda syntetiskt dokument och bokför en gång",
  approval: "Sparat mänskligt godkännande",
  approvalNote:
    "Godkännandet gäller en timme. Endast samma behöriga operatör kan verkställa det. Godkännandet ensamt utfärdar eller bokför inget.",
  expires: "Godkännandet löper ut",
  operator: "Godkännande operatör",
  blocked: "Hinder för verkställande",
  unavailable:
    "Det finns inget användbart godkännande. Granska aktuella uppgifter och godkänn innan du verkställer.",
  success:
    "Syntetiskt dokument utfärdat och kundfordran bokförd. Inget har skickats. SYN-numret är inte ett juridiskt fakturanummer.",
  posting: "Exakta föreslagna bokföringsrader",
  account: "Kontots ID",
  debit: "Debet i minsta valutaenhet",
  creditAmount: "Kredit i minsta valutaenhet",
  description: "Beskrivning",
  postingDate: "Bokföringsdatum",
  dueDate: "Förfallodatum",
  details: "Fullständig sparad granskning och kvitton",
  legal: "Begränsningar för verkliga företag kvarstår",
  draftFacts: "Fryst kommersiellt innehåll och exakta radberäkningar",
  commercialLines: "Frysta kommersiella rader",
  quantity: "Antal",
  base: "Grundbelopp i minsta valutaenhet",
  discount: "Rabatt i minsta valutaenhet",
  charge: "Avgift i minsta valutaenhet",
  tax: "Angiven skatt i minsta valutaenhet",
  sourceGross: "Källans bruttobelopp i minsta valutaenhet",
  evidence: "Sparat utkastunderlag",
  receipt: "Bokföringskvitto",
  register: "Fakturans ID i kundregistret",
  refresh: "Uppdatera sparat tillstånd",
  download: "Hämta exakt granskning och kvitto som JSON",
  recovery:
    "Använd sparade utkast- och gransknings-ID:n för återhämtning efter omladdning. Hämta begäran och återförsöksnyckeln innan du lämnar ett osäkert kommando. Starta inte ett nytt kommando för att gissa utfallet.",
  issued: "Utfärdad",
  pending: "Inte utfärdad",
  rules:
    "Det frysta utkastets hinder beskriver dess ursprungliga gräns. Denna separata syntetiska profil tar inte bort begränsningarna för juridisk identitet, fakturanummer eller skatt.",
};
export function invoiceIssueCopy(locale: Locale) {
  return locale === "sv" ? sv : en;
}
