import type { Locale } from "@/paraglide/runtime";

const en = {
  title: "Review invoice",
  boundary:
    "Synthetic books only. This review can issue an internal SYN document, post the two accounts you choose and register a customer receivable in one transaction. It does not issue a legal invoice, determine VAT or send a document.",
  requirements:
    "Use a complete customer draft with matching source totals and evidenced zero asserted tax. Both accounts are your explicit synthetic mapping. No real tax treatment or account classification is inferred.",
  openDraft: "Open draft for issue review",
  openReview: "Open saved issue review",
  prepare: "Prepare issue and posting review",
  control: "Receivables account (debit)",
  credit: "Revenue account (credit)",
  period: "Accounting period",
  series: "Voucher series",
  reason: "Reason for this issue and account choice",
  acknowledge: "I understand this is synthetic-only, not a legal invoice or VAT determination.",
  snapshot:
    "This form uses the displayed retained draft revision. Refreshing remote data does not replace it. If facts change, reopen the draft and prepare a new review.",
  history: "Saved issue reviews for this draft",
  empty: "No issue reviews have been prepared for this draft.",
  review: "Review and issue demo invoice",
  draft: "Draft",
  revision: "Revision",
  titleColumn: "Title",
  customer: "Customer",
  seller: "Seller",
  total: "Total",
  currency: "Currency",
  scale: "Currency scale",
  digest: "Review digest",
  internal: "Internal synthetic document",
  id: "Record ID",
  created: "Created at",
  approve: "Approve demo invoice and posting",
  execute: "Issue demo invoice",
  approval: "Retained human approval",
  approvalNote:
    "Approval lasts one hour. Only the same current operator can execute it. Approval alone does not issue or post.",
  expires: "Approval expires at",
  operator: "Approving operator",
  blocked: "Execution blockers",
  unavailable:
    "There is no usable approval. Review the current facts and approve before executing.",
  success:
    "Synthetic document issued and customer recognition posted. Nothing was delivered. The SYN number is not a legal invoice number.",
  posting: "Exact proposed journal lines",
  account: "Account",
  debit: "Debit",
  creditAmount: "Credit",
  description: "Description",
  postingDate: "Posting date",
  dueDate: "Due date",
  details: "Complete retained review and receipts",
  legal: "Real-company limitations remain",
  draftFacts: "Frozen commercial content and exact line calculations",
  commercialLines: "Frozen commercial lines",
  quantity: "Quantity",
  base: "Before tax",
  discount: "Discount",
  charge: "Charge",
  tax: "Tax amount",
  sourceGross: "Agreed total",
  evidence: "Retained draft evidence",
  receipt: "Posting receipt",
  register: "Customer register invoice ID",
  refresh: "Refresh status",
  download: "Download exact review and receipt JSON",
  recovery:
    "Use the saved draft and review IDs to recover after reload. Download the request and retry key before leaving an uncertain command. Do not start a new command to guess its outcome.",
  issued: "Issued",
  pending: "Not issued",
  rules:
    "Legal issue review requires both an active legal sales policy and a separately activated accrual/account-role profile, plus exact reviewed draft inputs. The retained flags describe activation limits; PDF capture and provider outcomes remain separate and do not activate or deliver an invoice.",
  legalHistory: "Legal issue history and artifacts",
  legalReadOnly:
    "Read-only inspection. This surface does not activate a legal policy or accounting profile, issue an invoice, render a PDF, contact a provider or send a document.",
  combinedActivation:
    "A legal sales policy alone is not an issuance activation. A saved review must bind the exact policy digest to a separately activated accrual and account-role profile, then pass the legal identity, date, period, account, line-tax and exact-total checks.",
  limitedProfile:
    "The separate legal prepare, approval and execute commands still require acknowledgeLimitedProfile. This inspector submits no acknowledgement or command.",
  policyActivations: "Legal policy activations",
  policyIdentity: "Policy identity and digest",
  policyReview: "Candidate and independent review",
  activationLimits: "Activation limits",
  issue: "Issue",
  legalCredit: "Credit",
  delivery: "Delivery",
  noPolicy: "No legal sales policy has been activated in this book.",
  notAvailable: "Not available",
  legalReviews: "Immutable legal issue reviews",
  legalReview: "Legal issue review",
  noLegalReview: "No legal issue review has been prepared for this draft.",
  legalNumber: "Legal document number",
  notIssued: "Not issued",
  immutableIdentities: "Immutable draft, review and issue identities",
  draftIdentity: "Draft identity, revision and digest",
  issueIdentity: "Issue identity and digest",
  approvalIdentity: "Latest approval identity",
  legalStatesAndTotals: "Independent legal states and exact totals",
  recognized: "Recognized in accounting",
  deliveredState: "Delivered",
  yes: "Yes",
  no: "No",
  net: "Net",
  legalTax: "VAT",
  gross: "Gross",
  activationPair: "Combined policy and accounting-profile activation",
  legalPolicy: "Legal policy",
  accountingProfile: "Accounting profile",
  sameActivationOperator:
    "Blocker: the policy and accounting profile show the same activating operator; the reviewed legal path requires separate operators.",
  noActivationPair:
    "No saved legal review binds an accounting profile to this draft. This read-only surface cannot create that binding.",
  legalInputBlockers: "Legal-input and current-dependency blockers",
  noReadBlockers: "No unresolved blocker is exposed by the retained draft or selected review.",
  legalArtifacts: "Immutable legal PDF artifacts",
  noIssueForArtifacts: "A legal issue is required before a legal PDF can exist.",
  legalPdfHistory: "Legal PDF capture history",
  pdfCapture: "PDF capture",
  captureDigest: "Capture digest",
  sealedArtifact: "Sealed artifact",
  sha256: "Artifact SHA-256",
  notSealed: "Captured, not sealed",
  artifactHash: "Artifact hash",
  artifactBytes: "Artifact bytes",
  renderer: "Renderer version",
  downloadPdf: "Download verified PDF (not delivery)",
  pdfVerified: "The downloaded bytes match the retained length, SHA-256 and PDF signature.",
  pdfCaptured: "The source is captured, but no sealed PDF artifact is available.",
  noPdf: "No legal PDF has been captured for this issue.",
  deliveryHistory: "Read-only delivery and provider history",
  noPdfForDelivery: "No sealed PDF history is available for delivery inspection.",
  deliveryRequest: "Delivery request",
  deliveryStatus: "Delivery status",
  sendAuthorized: "Send handoff authorized",
  providerPayload: "Provider payload ready",
  providerAttempts: "Provider attempt history",
  attempt: "Attempt",
  providerRequest: "Provider request ID",
  externalTraffic: "External traffic proven",
  providerOutcome: "Provider outcome",
  notReconciled: "Not reconciled",
  noProviderAttempts: "No provider attempt has been started.",
  noDelivery: "No delivery request exists for this PDF.",
  providerNotDelivery:
    "Provider acceptance, rejection or an unknown attempt is not customer delivery. Every retained delivery state remains false.",
  missingIssueIdentity:
    "Blocker: this legal registered invoice has no legal issue identity, so its legal history cannot be inspected.",
  draftSnapshot: "Complete immutable draft snapshot",
  reviewSnapshot: "Complete legal review, approval, blocker and state record",
  issueSnapshot: "Complete immutable legal issue receipt",
};
const sv: typeof en = {
  title: "Granska faktura",
  boundary:
    "Endast syntetiska böcker. Granskningen kan skapa ett internt SYN-dokument, bokföra de två konton du väljer och registrera en kundfordran i samma transaktion. Den utfärdar ingen juridisk faktura, bedömer inte moms och skickar inget dokument.",
  requirements:
    "Använd ett komplett kundutkast med avstämda källbelopp och styrkt skattebelopp noll. Båda kontona är ditt uttryckliga syntetiska val. Ingen verklig skattebehandling eller kontoklassificering antas.",
  openDraft: "Öppna utkast för granskning",
  openReview: "Öppna sparad utfärdandegranskning",
  prepare: "Förbered utfärdande och bokföring",
  control: "Kundfordringskonto (debet)",
  credit: "Intäktskonto (kredit)",
  period: "Bokföringsperiod",
  series: "Verifikationsserie",
  reason: "Skäl för utfärdandet och kontovalet",
  acknowledge:
    "Jag förstår att detta endast är syntetiskt, inte en juridisk faktura eller momsbedömning.",
  snapshot:
    "Formuläret använder den visade sparade utkastrevisionen. Uppdatering av serverdata ersätter den inte. Om uppgifterna ändras, öppna utkastet igen och förbered en ny granskning.",
  history: "Sparade utfärdandegranskningar för utkastet",
  empty: "Inga utfärdandegranskningar har förberetts för utkastet.",
  review: "Granska och utfärda demofaktura",
  draft: "Utkast",
  revision: "Revision",
  titleColumn: "Titel",
  customer: "Kund",
  seller: "Säljare",
  total: "Totalt",
  currency: "Valuta",
  scale: "Valutans decimaler",
  digest: "Granskningens kontrollsumma",
  internal: "Internt syntetiskt dokument",
  id: "Postens ID",
  created: "Skapad",
  approve: "Godkänn demofaktura och bokföring",
  execute: "Utfärda demofaktura",
  approval: "Sparat mänskligt godkännande",
  approvalNote:
    "Godkännandet gäller en timme. Endast samma behöriga operatör kan verkställa det. Godkännandet ensamt utfärdar eller bokför inget.",
  expires: "Godkännandet löper ut",
  operator: "Godkännande operatör",
  blocked: "Hinder för verkställande",
  unavailable:
    "Det finns inget användbart godkännande. Granska aktuella uppgifter och godkänn innan du verkställer.",
  success:
    "Syntetiskt dokument utfärdat och kundfordran bokförd. Inget har skickats. SYN-numret är inte ett juridiskt fakturanummer.",
  posting: "Exakta föreslagna bokföringsrader",
  account: "Konto",
  debit: "Debet",
  creditAmount: "Kredit",
  description: "Beskrivning",
  postingDate: "Bokföringsdatum",
  dueDate: "Förfallodatum",
  details: "Fullständig sparad granskning och kvitton",
  legal: "Begränsningar för verkliga företag kvarstår",
  draftFacts: "Fryst kommersiellt innehåll och exakta radberäkningar",
  commercialLines: "Frysta kommersiella rader",
  quantity: "Antal",
  base: "Exkl. moms",
  discount: "Rabatt",
  charge: "Tillägg",
  tax: "Momsbelopp",
  sourceGross: "Avtalat totalbelopp",
  evidence: "Sparat utkastunderlag",
  receipt: "Bokföringskvitto",
  register: "Fakturans ID i kundregistret",
  refresh: "Uppdatera status",
  download: "Hämta exakt granskning och kvitto som JSON",
  recovery:
    "Använd sparade utkast- och gransknings-ID:n för återhämtning efter omladdning. Hämta begäran och återförsöksnyckeln innan du lämnar ett osäkert kommando. Starta inte ett nytt kommando för att gissa utfallet.",
  issued: "Utfärdad",
  pending: "Inte utfärdad",
  rules:
    "En granskning av juridisk utfärdande kräver både en aktiv juridisk säljpolicy och en separat aktiverad faktureringsmetod- och kontorollprofil samt exakta granskade utkastuppgifter. Sparade begränsningar beskriver aktiveringsgränserna. PDF-inspelning och leverantörsutfall förblir separata och aktiverar eller levererar inte någon faktura.",
  legalHistory: "Historik och artefakter för juridisk utfärdande",
  legalReadOnly:
    "Endast läsning. Ytan aktiverar ingen juridisk policy eller bokföringsprofil, utfärdar ingen faktura, renderar ingen PDF, kontaktar ingen leverantör och skickar inget dokument.",
  combinedActivation:
    "En juridisk säljpolicy är inte i sig en aktivering för utfärdande. En sparad granskning måste binda policyns digest till en separat aktiverad faktureringsmetod- och kontorollprofil och passera kontrollerna av juridisk identitet, datum, period, konto, radmoms och exakta totalbelopp.",
  limitedProfile:
    "De separata kommandona för juridisk förberedelse, godkännande och verkställande kräver fortfarande acknowledgeLimitedProfile. Den här granskningen skickar varken bekräftelse eller kommando.",
  policyActivations: "Aktiverade juridiska policies",
  policyIdentity: "Policyidentitet och digest",
  policyReview: "Kandidat och oberoende granskning",
  activationLimits: "Aktiveringsgränser",
  issue: "Utfärdande",
  legalCredit: "Kredit",
  delivery: "Leverans",
  noPolicy: "Ingen juridisk säljpolicy har aktiverats i den här boken.",
  notAvailable: "Inte tillgängligt",
  legalReviews: "Oföränderliga granskningar av juridisk utfärdande",
  legalReview: "Granskning av juridisk utfärdande",
  noLegalReview: "Ingen granskning av juridisk utfärdande har förberetts för det här utkastet.",
  legalNumber: "Juridiskt dokumentnummer",
  notIssued: "Inte utfärdad",
  immutableIdentities: "Oföränderliga identiteter för utkast, granskning och utfärdande",
  draftIdentity: "Utkastidentitet, revision och digest",
  issueIdentity: "Utfärdandeidentitet och digest",
  approvalIdentity: "Senaste godkännandeidentitet",
  legalStatesAndTotals: "Oberoende juridiska tillstånd och exakta totalbelopp",
  recognized: "Bokförd i redovisningen",
  deliveredState: "Levererad",
  yes: "Ja",
  no: "Nej",
  net: "Netto",
  legalTax: "Moms",
  gross: "Brutto",
  activationPair: "Kombinerad aktivering av policy och bokföringsprofil",
  legalPolicy: "Juridisk policy",
  accountingProfile: "Bokföringsprofil",
  sameActivationOperator:
    "Hinder: policy och bokföringsprofil visar samma aktiverande operatör. Den granskade juridiska vägen kräver separata operatörer.",
  noActivationPair:
    "Ingen sparad juridisk granskning binder en bokföringsprofil till det här utkastet. Den skrivskyddade ytan kan inte skapa den bindningen.",
  legalInputBlockers: "Hinder i juridiska uppgifter och aktuella beroenden",
  noReadBlockers: "Det bevarade utkastet eller den valda granskningen visar inget olöst hinder.",
  legalArtifacts: "Oföränderliga juridiska PDF-artefakter",
  noIssueForArtifacts: "Juridisk utfärdande måste finnas innan en juridisk PDF kan finnas.",
  legalPdfHistory: "Historik för juridiska PDF-inspelningar",
  pdfCapture: "PDF-inspelning",
  captureDigest: "Digest för inspelning",
  sealedArtifact: "Förseglad artefakt",
  sha256: "Artefaktens SHA-256",
  notSealed: "Inspelad, inte förseglad",
  artifactHash: "Artefaktens hash",
  artifactBytes: "Artefaktens byteantal",
  renderer: "Renderarversion",
  downloadPdf: "Hämta verifierad PDF (inte leverans)",
  pdfVerified: "Hämtade bytes matchar bevarad längd, SHA-256 och PDF-signatur.",
  pdfCaptured: "Källan är inspelad, men ingen förseglad PDF-artefakt finns.",
  noPdf: "Ingen juridisk PDF har inspelats för det här utfärdandet.",
  deliveryHistory: "Skrivskyddad leverans- och leverantörshistorik",
  noPdfForDelivery: "Ingen förseglad PDF-historik finns att inspektera för leverans.",
  deliveryRequest: "Leveransbegäran",
  deliveryStatus: "Leveransstatus",
  sendAuthorized: "Överlämning avsändning godkänd",
  providerPayload: "Leverantörspayload klar",
  providerAttempts: "Historik över leverantörsförsök",
  attempt: "Försök",
  providerRequest: "Leverantörens begäran-ID",
  externalTraffic: "Extern trafik styrkt",
  providerOutcome: "Leverantörens utfall",
  notReconciled: "Inte avstämd",
  noProviderAttempts: "Inget leverantörsförsök har startats.",
  noDelivery: "Ingen leveransbegäran finns för den här PDF-filen.",
  providerNotDelivery:
    "Leverantörens godkännande, avslag eller okänt försök är inte kundleverans. Alla bevarade leveranstillstånd förblir falska.",
  missingIssueIdentity:
    "Hinder: den här juridiskt registrerade fakturan saknar identitet för juridisk utfärdande, så dess juridiska historik inte kan inspekteras.",
  draftSnapshot: "Fullständigt oföränderligt utkast",
  reviewSnapshot: "Fullständig juridisk granskning, godkännande, hinder och tillstånd",
  issueSnapshot: "Fullständigt oföränderligt kvitto för juridisk utfärdande",
};
export function invoiceIssueCopy(locale: Locale) {
  return locale === "sv" ? sv : en;
}
