import type { Locale } from "@/paraglide/runtime";

const en = {
  title: "Undo payment match",
  back: "Back to payment match",
  undo: "Undo this match",
  matched: "Payment matched",
  released: "Match undone",
  refresh: "Refresh",
  effect:
    "This reopens the matched invoice amounts and makes the payment available to match again. It does not change the original posting or refund any money.",
  whole: "The whole match will be undone, including every invoice shown below.",
  amount: "Amount to unmatch",
  releasedAmount: "Unmatched amount",
  invoice: "Invoice",
  before: "Before undo",
  after: "Outstanding after undo",
  paymentAfter: "Payment available after undo",
  reason: "Reason for undoing this match",
  prepare: "Review undo",
  approve: "Approve undo",
  execute: "Confirm undo",
  acknowledge:
    "I reviewed all affected invoices and amounts. I understand this does not refund the payment.",
  stale:
    "The invoice, payment or accounting period has changed. This saved review can no longer be confirmed.",
  newReview: "Create a new review",
  approved: "Approved until",
  expired: "The approval has expired. Review the amounts and approve again.",
  operator: "An operator needs to approve this review before the match can be undone.",
  completed: "The invoice balance and available payment have been updated.",
  history: "Previous undo reviews",
  approvalHistory: "Approval history",
  revoked: "Approval withdrawn",
  withdraw: "Withdraw approval",
  withdrawReason: "Reason for withdrawing approval",
  source: "Payment source",
  details: "Technical details",
  review: "Review undo",
  currentBalance: "Invoice outstanding",
  matchedAmount: "Matched amount",
  completedAt: "Undone on",
};
const sv: typeof en = {
  title: "Ångra betalningsmatchning",
  back: "Tillbaka till betalningsmatchningen",
  undo: "Ångra matchningen",
  matched: "Betalningen är matchad",
  released: "Matchningen har ångrats",
  refresh: "Uppdatera",
  effect:
    "De matchade fakturabeloppen blir utestående och betalningen kan matchas igen. Den ursprungliga bokföringen ändras inte och inga pengar återbetalas.",
  whole: "Hela matchningen ångras, inklusive alla fakturor som visas nedan.",
  amount: "Belopp att frigöra",
  releasedAmount: "Frigjort belopp",
  invoice: "Faktura",
  before: "Före återföring",
  after: "Utestående efter återföring",
  paymentAfter: "Tillgänglig betalning efter återföring",
  reason: "Varför ska matchningen ångras?",
  prepare: "Granska återföring",
  approve: "Godkänn återföring",
  execute: "Bekräfta återföring",
  acknowledge:
    "Jag har granskat alla berörda fakturor och belopp. Jag förstår att betalningen inte återbetalas.",
  stale:
    "Fakturan, betalningen eller bokföringsperioden har ändrats. Den sparade granskningen kan inte längre bekräftas.",
  newReview: "Skapa ny granskning",
  approved: "Godkänt till",
  expired: "Godkännandet har löpt ut. Granska beloppen och godkänn igen.",
  operator: "En operatör behöver godkänna granskningen innan matchningen kan ångras.",
  completed: "Fakturans saldo och den tillgängliga betalningen har uppdaterats.",
  history: "Tidigare granskningar av återföring",
  approvalHistory: "Godkännandehistorik",
  revoked: "Godkännandet har återkallats",
  withdraw: "Återkalla godkännande",
  withdrawReason: "Varför ska godkännandet återkallas?",
  source: "Betalningsunderlag",
  details: "Tekniska detaljer",
  review: "Granska återföring",
  currentBalance: "Kvar på fakturan",
  matchedAmount: "Matchat belopp",
  completedAt: "Ångrad den",
};
export function paymentUndoCopy(locale: Locale) {
  return locale === "sv" ? sv : en;
}
