export const english = {
  title: "Set up your company",
  intro: "Save what you know now. Return here whenever you have the next piece.",
  identity: "Company details",
  accounting: "Accounting settings",
  history: "Previous bookkeeping",
  banking: "Banking",
  review: "Next steps",
  name: "Company name",
  legalForm: "Legal form",
  organizationNumber: "Organization or personal identity number",
  numberHint: "Use 10 digits, without spaces or a hyphen.",
  unknown: "Not decided yet",
  limited: "Limited company (aktiebolag)",
  sole: "Sole trader (enskild firma)",
  accountingMethod: "Accounting method",
  accrual: "Accrual method",
  cash: "Cash method",
  vatRegistered: "Registered for VAT",
  yes: "Yes",
  no: "No",
  vatPeriod: "VAT reporting period",
  monthly: "Monthly",
  quarterly: "Quarterly",
  yearly: "Yearly",
  fiscalYearStartsOn: "Fiscal year starts",
  fiscalYearEndsOn: "Fiscal year ends",
  historyQuestion: "How will you bring your books into OpenERP?",
  newBusiness: "New business",
  newBusinessHint: "Start with no previous bookkeeping to migrate.",
  sie: "Import a SIE file",
  sieHint: "Keep your previous system’s accounts, balances and vouchers for review.",
  opening: "Opening balances",
  openingHint: "Bring reviewed balances and outstanding invoices from another system.",
  bankQuestion: "How would you like to add bank transactions?",
  connect: "Connect a bank",
  connectHint: "Choose a provider, give consent and map your account.",
  file: "Import a statement",
  fileHint: "Upload transactions when a bank connection is unavailable.",
  later: "Decide later",
  laterHint: "Continue setup and return to banking when you are ready.",
  next: "Save and continue",
  save: "Save details",
  back: "Back",
  saved: "Details saved",
  unsaved: "Unsaved changes",
  incomplete: "Details still needed",
  recorded: "Company details recorded",
  recordedHint:
    "These are the details you supplied. Accounting support, historical records and bank coverage are checked separately.",
  profilePending: "Accounting support needs review before you can post entries for this company.",
  reload: "Reload saved details",
  retry: "Try again",
  validation: "Check the highlighted details before saving.",
  dates: "The fiscal year must end on or after its start date.",
  readOnly: "You can view these details. An operator can change them.",
  finish: "Open company",
  bankOptional: "Banking is optional during setup.",
};
export const swedish: typeof english = {
  title: "Ställ in ditt företag",
  intro: "Spara de uppgifter du har. Kom tillbaka när du kan fylla i resten.",
  identity: "Företagsuppgifter",
  accounting: "Bokföringsinställningar",
  history: "Tidigare bokföring",
  banking: "Bank",
  review: "Nästa steg",
  name: "Företagsnamn",
  legalForm: "Företagsform",
  organizationNumber: "Organisations- eller personnummer",
  numberHint: "Ange 10 siffror utan mellanslag eller bindestreck.",
  unknown: "Inte bestämt ännu",
  limited: "Aktiebolag",
  sole: "Enskild firma",
  accountingMethod: "Bokföringsmetod",
  accrual: "Faktureringsmetoden",
  cash: "Kontantmetoden",
  vatRegistered: "Momsregistrerad",
  yes: "Ja",
  no: "Nej",
  vatPeriod: "Momsperiod",
  monthly: "Månad",
  quarterly: "Kvartal",
  yearly: "År",
  fiscalYearStartsOn: "Räkenskapsåret börjar",
  fiscalYearEndsOn: "Räkenskapsåret slutar",
  historyQuestion: "Hur vill du föra över bokföringen till OpenERP?",
  newBusiness: "Nytt företag",
  newBusinessHint: "Börja utan tidigare bokföring att föra över.",
  sie: "Importera en SIE-fil",
  sieHint: "Behåll konton, saldon och verifikationer från ditt tidigare system för granskning.",
  opening: "Ingående balanser",
  openingHint: "För över granskade saldon och obetalda fakturor från ett annat system.",
  bankQuestion: "Hur vill du lägga till banktransaktioner?",
  connect: "Anslut en bank",
  connectHint: "Välj leverantör, ge samtycke och koppla bankkontot.",
  file: "Importera kontoutdrag",
  fileHint: "Ladda upp transaktioner när bankanslutning saknas.",
  later: "Bestäm senare",
  laterHint: "Fortsätt med inställningarna och återkom till banken när du är redo.",
  next: "Spara och fortsätt",
  save: "Spara uppgifter",
  back: "Tillbaka",
  saved: "Uppgifterna sparade",
  unsaved: "Osparade ändringar",
  incomplete: "Uppgifter saknas",
  recorded: "Företagsuppgifterna registrerade",
  recordedHint:
    "Detta är uppgifterna du har angett. Bokföringsstöd, tidigare bokföring och bankunderlag kontrolleras separat.",
  profilePending: "Bokföringsstödet behöver granskas innan du kan bokföra för företaget.",
  reload: "Läs in sparade uppgifter",
  retry: "Försök igen",
  validation: "Kontrollera de markerade uppgifterna innan du sparar.",
  dates: "Räkenskapsåret måste sluta på eller efter startdagen.",
  readOnly: "Du kan se uppgifterna. En operatör kan ändra dem.",
  finish: "Öppna företaget",
  bankOptional: "Bankanslutning är valfri under inställningen.",
};
