import * as stylex from "@stylexjs/stylex";

export const tokens = stylex.defineConsts({
  accent: "var(--accent)",
  accentForeground: "var(--accent-foreground)",
  background: "var(--background)",
  blurSmall: "var(--blur-small)",
  border: "var(--border)",
  borderActive: "var(--border-active)",
  card: "var(--card)",
  workspaceSurface: "var(--workspace-surface)",
  cardForeground: "var(--card-foreground)",
  controlBackground: "var(--control-background)",
  controlDisabledBackground: "var(--control-disabled-background)",
  controlInvalidBorder: "var(--control-invalid-border)",
  controlInvalidRing: "var(--control-invalid-ring)",
  destructive: "var(--destructive)",
  destructiveForeground: "var(--destructive-foreground)",
  destructiveBackground: "var(--destructive-background)",
  destructiveHoverBackground: "var(--destructive-hover-background)",
  durationFast: "var(--duration-fast)",
  durationMedium: "var(--duration-medium)",
  durationQuick: "var(--duration-quick)",
  durationSlow: "var(--duration-slow)",
  easeOut: "var(--ease-out)",
  easeSmoothOut: "var(--ease-smooth-out)",
  foreground: "var(--foreground)",
  ghostHoverBackground: "var(--ghost-hover-background)",
  fontSerif: "var(--font-serif)",
  fontSizeBrand: "1.1875rem",
  fontSizeTask: "0.84375rem",
  fontSizeEmptyTitle: "1.375rem",
  trackingSerif: "-0.02em",
  trackingSection: "0.08em",
  lineHeight32Px: "2rem",
  lineHeight30Px: "1.875rem",
  lineHeight21Px: "1.3125rem",
  menuBackdrop: "rgba(0, 0, 0, 0.2)",
  radiusSheetTop: "12px 12px 0 0",
  fontMono: "var(--font-mono)",
  fontSizeSm: "0.875rem",
  fontSizeBase: "1rem",
  fontSizeMd: "1rem",
  fontSizeXl: "1.25rem",
  fontSize2xl: "1.5rem",
  fontSize3xl: "1.875rem",
  fontSize4xl: "2.25rem",
  fontSize6xl: "3.75rem",
  fontWeightNormal: "400",
  fontWeightMedium: "500",
  fontWeightSemibold: "600",
  fontWeightBold: "700",
  focusRing: "0 0 0 2px var(--ring)",
  focusRingInset: "inset 0 0 0 2px var(--ring)",
  inheritedColor: "inherit",
  input: "var(--input)",
  muted: "var(--muted)",
  mutedForeground: "var(--muted-foreground)",
  outlineBackground: "var(--outline-background)",
  outlineContentHoverBackground: "var(--outline-content-hover-background)",
  outlineHoverBackground: "var(--outline-hover-background)",
  popover: "var(--popover)",
  popoverForeground: "var(--popover-foreground)",
  primary: "var(--primary)",
  primaryForeground: "var(--primary-foreground)",
  radius: "var(--radius)",
  radiusNone: "0",
  radius2xl: "var(--radius-2xl)",
  radiusControl: "var(--radius-control)",
  radiusLg: "var(--radius-lg)",
  radiusMd: "var(--radius-md)",
  radiusOverlay: "var(--radius-overlay)",
  radiusSm: "var(--radius-sm)",
  radiusSurface: "var(--radius-surface)",
  radiusXl: "var(--radius-xl)",
  radiusFull: "9999px",
  ring: "var(--ring)",
  secondary: "var(--secondary)",
  secondaryForeground: "var(--secondary-foreground)",
  selectionIndicator: "inset 3px 0 0 var(--primary)",
  scaleLarge: "var(--scale-large)",
  scaleMedium: "var(--scale-medium)",
  scaleSmall: "var(--scale-small)",
  scaleTiny: "var(--scale-tiny)",
  shadow2xl: "var(--shadow-2xl)",
  shadowNone: "none",
  shadowFloating: "var(--shadow-floating)",
  shadowLg: "var(--shadow-lg)",
  shadowMd: "var(--shadow-md)",
  shadowOverlay: "var(--shadow-overlay)",
  shadowRaised: "var(--shadow-raised)",
  shadowSm: "var(--shadow-sm)",
  shadowXl: "var(--shadow-xl)",
  shadowXs: "var(--shadow-xs)",
  sidebar: "var(--sidebar)",
  sidebarAccent: "var(--sidebar-accent)",
  sidebarBorder: "var(--sidebar-border)",
  sidebarForeground: "var(--sidebar-foreground)",
  sidebarRing: "var(--sidebar-ring)",
  success: "var(--success)",
  successBorder: "var(--success-border)",
  successForeground: "var(--success-foreground)",
  space0: "0",
  space1: "0.25rem",
  space2: "0.5rem",
  space3: "0.75rem",
  space4: "1rem",
  space6: "1.5rem",
  space8: "2rem",
  space12: "3rem",
  space16: "4rem",
  space24: "6rem",
  tintedBackground: "var(--tinted-background)",
  tintedHoverBackground: "var(--tinted-hover-background)",
  surfaceDefault: "var(--surface-default)",
  surfaceHover: "var(--surface-hover)",
  transparent: "transparent",
  lineHeightNormal: "1.5",
  lineHeightHeading: "1.25",
  lineHeightCompact: "1.15",
  lineHeightTight: "1",
  warning: "var(--warning)",
  warningBorder: "var(--warning-border)",
  warningForeground: "var(--warning-foreground)",
  space0_25: "0.0625rem",
  fontSizeXs: "0.75rem",
  lineHeightBodyCompact: "1.4",
  space2_5: "0.625rem",
  space1_5: "0.375rem",
  space0_5: "0.125rem",
  radiusCircle: "50%",
  fontSizeCompact: "0.6875rem",
  lineHeightRelaxed: "1.625",
  durationControl: "100ms",
  buttonFocusShadow: "0 0 0 2px color-mix(in oklch, var(--ring) 30%, transparent)",
  primaryHoverBackground: "color-mix(in oklch, var(--primary) 80%, transparent)",
  secondaryHoverBackground: "color-mix(in oklch, var(--secondary), var(--foreground) 5%)",
  destructiveSolidHoverBackground: "color-mix(in oklch, var(--destructive) 88%, black)",
  space9: "2.25rem",
  controlFocusShadow: "0 0 0 2px color-mix(in oklch, var(--ring) 25%, transparent)",
  trackingCompact: "-0.01em",
  spaceNegative0_5: "-0.125rem",
  radiusSmallControl: "4px",
  radiusDetail: "2px",
  spaceNegative1: "-0.25rem",
  radiusCheckbox: "5px",
  radiusSwatch: "calc(var(--radius) - 3px)",
  space11: "2.75rem",
  trackingWider: "0.05em",
  trackingLabel: "0.02em",
  fontSizeControl: "0.8125rem",
  lineHeightBody: "1.45",
  space5: "1.25rem",
  space7: "1.75rem",
  trackingWidest: "0.1em",
  trackingHeading: "-0.025em",
  spaceNegative3: "-0.75rem",
  fontSize2xs: "0.625rem",
  space0_75: "0.1875rem",
  easeDefault: "ease",
  lineHeight20Px: "1.25rem",
  lineHeight16Px: "1rem",
  durationPanel: "200ms",
  easeMenuEnter: "cubic-bezier(0.23, 1, 0.32, 1)",
  easeMenuExit: "cubic-bezier(0.7, 0, 0.84, 0)",
  space3_5: "0.875rem",
  trackingWide: "0.025em",
  space14: "3.5rem",
  space10: "2.5rem",
  radiusFullscreen: "16px",
  lineHeightLabel: "1.35",
  space18: "4.5rem",
  fontSizeLg: "1.125rem",
  lineHeightReading: "1.6",
  durationFeedback: "120ms",
  space1_75: "0.4375rem",
  trackingCaps: "0.04em",
  spaceNegative2: "-0.5rem",
  lineHeight24Px: "1.5rem",
  lineHeightTitle: "1.2",
  lineHeight28Px: "1.75rem",
  space2_6: "0.65rem",
  space2_4: "0.6rem",
  space1_4: "0.35rem",
  spaceNegative4: "-1rem",
  space20: "5rem",
  lineHeight18Px: "1.125rem",
  fontSize5xl: "3rem",
  trackingDisplayTight: "-0.035em",
  lineHeightDisplayCompact: "1.1",
  lineHeightDisplay: "1.04",
  fontSizeDisplaySmall: "2rem",
  fontWeightEmphasis: "650",
  trackingDisplay: "-0.03em",
  fontSizeBody: "0.9375rem",
  mutedAlpha45: "color-mix(in oklch, var(--muted) 45%, transparent)",
  mutedAlpha35: "color-mix(in oklch, var(--muted) 35%, transparent)",
  durationPulse: "2s",
  mutedAlpha50: "color-mix(in oklch, var(--muted) 50%, transparent)",
  destructiveAlpha30: "color-mix(in oklch, var(--destructive) 30%, transparent)",
  primaryAlpha10: "color-mix(in oklch, var(--primary) 10%, transparent)",
  foregroundAlpha20: "color-mix(in oklch, var(--foreground) 20%, transparent)",
  mutedAlpha20: "color-mix(in oklch, var(--muted) 20%, transparent)",
  shadowSmOutlined:
    "var(--shadow-sm), 0 0 0 1px color-mix(in oklch, var(--foreground) 8%, transparent)",
  mutedForegroundAlpha70: "color-mix(in oklch, var(--muted-foreground) 70%, transparent)",
  controlInvalidShadowThin: "0 0 0 1px var(--control-invalid-ring)",
  shadowFloatingOutlined:
    "var(--shadow-floating), 0 0 0 1px color-mix(in oklch, var(--foreground) 10%, transparent)",
  mutedAlpha15: "color-mix(in oklch, var(--muted) 15%, transparent)",
  mutedAlpha60: "color-mix(in oklch, var(--muted) 60%, transparent)",
  primaryAlpha15: "color-mix(in oklch, var(--primary) 15%, transparent)",
  destructiveAlpha5: "color-mix(in oklch, var(--destructive) 5%, transparent)",
  destructiveAlpha25: "color-mix(in oklch, var(--destructive) 25%, transparent)",
  borderShadowSubtle: "0 0 0 1px color-mix(in oklch, var(--foreground) 6%, transparent)",
  durationSpin: "1s",
  primaryAlpha14: "color-mix(in oklch, var(--primary) 14%, transparent)",
  focusShadowMedium: "0 0 0 2px color-mix(in oklch, var(--ring) 40%, transparent)",
  destructiveAlpha55: "color-mix(in oklch, var(--destructive) 55%, transparent)",
  warningBorderAlpha70: "color-mix(in oklch, var(--warning-border) 70%, transparent)",
  sidebarAlpha60: "color-mix(in oklch, var(--sidebar) 60%, transparent)",
  borderShadowStrong: "0 0 0 1px color-mix(in oklch, var(--foreground) 10%, transparent)",
  borderShadowSoft: "0 0 0 1px color-mix(in oklch, var(--foreground) 8%, transparent)",
  shadowLgOutlined:
    "var(--shadow-lg), 0 0 0 1px color-mix(in oklch, var(--foreground) 10%, transparent)",
  invalidShadowThin: "0 0 0 1px color-mix(in oklch, var(--destructive) 40%, transparent)",
  borderInsetShadow: "inset 0 0 0 1px var(--border)",
  mutedAlpha40: "color-mix(in oklch, var(--muted) 40%, transparent)",
  invalidShadowInset: "inset 0 0 0 1px color-mix(in oklch, var(--destructive) 50%, transparent)",
  dropBeforeShadow: "inset 0 2px 0 var(--primary)",
  dropAfterShadow: "inset 0 -2px 0 var(--primary)",
  foregroundAlpha70: "color-mix(in oklch, var(--foreground) 70%, transparent)",
  destructiveAlpha10: "color-mix(in oklch, var(--destructive) 10%, transparent)",
  overlayBackdrop: "rgba(0, 0, 0, 0.5)",
  primaryAlpha8: "color-mix(in oklch, var(--primary) 8%, transparent)",
  primaryAlpha42: "color-mix(in oklch, var(--primary) 42%, transparent)",
  cardOnMuted92: "color-mix(in oklch, var(--card) 92%, var(--muted))",
  primaryAlpha12: "color-mix(in oklch, var(--primary) 12%, transparent)",
  focusShadowThin: "0 0 0 1px color-mix(in oklch, var(--ring) 50%, transparent)",
  destructiveAlpha80: "color-mix(in oklch, var(--destructive) 80%, transparent)",
  mutedAlpha25: "color-mix(in oklch, var(--muted) 25%, transparent)",
  controlInvalidShadow: "0 0 0 2px var(--control-invalid-ring)",
  radiusPanelTop: "var(--radius-lg) var(--radius-lg) 0 0",
  mutedAlpha90: "color-mix(in oklch, var(--muted) 90%, transparent)",
  invalidShadowStrong: "0 0 0 2px color-mix(in oklch, var(--destructive) 70%, transparent)",
  backgroundAlpha95: "color-mix(in oklch, var(--background) 95%, transparent)",
  destructiveFocusShadow: "0 0 0 2px color-mix(in oklch, var(--destructive) 20%, transparent)",
  primaryAlpha20: "color-mix(in oklch, var(--primary) 20%, transparent)",
  primaryAlpha30: "color-mix(in oklch, var(--primary) 30%, transparent)",
  accentAlpha50: "color-mix(in oklch, var(--accent) 50%, transparent)",
  foregroundAlpha50: "color-mix(in oklch, var(--foreground) 50%, transparent)",
  foregroundAlpha30: "color-mix(in oklch, var(--foreground) 30%, transparent)",
  foregroundAlpha40: "color-mix(in oklch, var(--foreground) 40%, transparent)",
  foregroundAlpha45: "color-mix(in oklch, var(--foreground) 45%, transparent)",
  foregroundAlpha35: "color-mix(in oklch, var(--foreground) 35%, transparent)",
  borderAlpha50: "color-mix(in oklch, var(--border) 50%, transparent)",
  sidebarFocusShadow: "0 0 0 2px var(--sidebar-ring)",
  mutedAlpha30: "color-mix(in oklch, var(--muted) 30%, transparent)",
  shadowXlOutlined:
    "var(--shadow-xl), 0 0 0 1px color-mix(in oklch, var(--foreground) 10%, transparent)",
  mediaBackground: "black",
  mediaForeground: "white",
  focusShadowThinSoft: "0 0 0 1px color-mix(in oklch, var(--ring) 25%, transparent)",
  destructiveAlpha50: "color-mix(in oklch, var(--destructive) 50%, transparent)",
  borderShadow: "0 0 0 1px var(--border)",
  fontMonospaceFallback: "monospace",
  primaryAlpha5: "color-mix(in oklch, var(--primary) 5%, transparent)",
  primaryAlpha45: "color-mix(in oklch, var(--primary) 45%, transparent)",
  focusInsetShadowThin: "inset 0 0 0 1px var(--ring)",
  mutedForegroundAlpha45: "color-mix(in oklch, var(--muted-foreground) 45%, transparent)",
  destructiveAlpha40: "color-mix(in oklch, var(--destructive) 40%, transparent)",
  primaryOnBackground6: "color-mix(in oklch, var(--primary) 6%, var(--background))",
  primaryOnBorder24: "color-mix(in oklch, var(--primary) 24%, var(--border))",
  successOnBackground7: "color-mix(in oklch, var(--success) 7%, var(--background))",
  successOnBorder28: "color-mix(in oklch, var(--success) 28%, var(--border))",
  warningOnBackground8: "color-mix(in oklch, var(--warning) 8%, var(--background))",
  warningOnBorder30: "color-mix(in oklch, var(--warning) 30%, var(--border))",
  destructiveOnBackground7: "color-mix(in oklch, var(--destructive) 7%, var(--background))",
  destructiveOnBorder30: "color-mix(in oklch, var(--destructive) 30%, var(--border))",
  currentColorWash: "color-mix(in srgb, currentColor 5%, transparent)",
  avatarSeparationShadow: "0 0 0 2px var(--card)",
  accentAlpha55: "color-mix(in oklch, var(--accent) 55%, transparent)",
  focusShadowStrong: "0 0 0 2px color-mix(in oklch, var(--ring) 50%, transparent)",
  focusShadowWide: "0 0 0 3px color-mix(in oklch, var(--ring) 50%, transparent)",
  shadowMdOutlined:
    "var(--shadow-md), 0 0 0 1px color-mix(in oklch, var(--foreground) 10%, transparent)",
  accentAlpha60: "color-mix(in oklch, var(--accent) 60%, transparent)",
  sheetBackdrop: "rgba(0, 0, 0, 0.45)",
  controlHeightXs: "1.5rem",
  controlHeightSm: "1.75rem",
  controlHeight: "2rem",
  controlHeightLg: "2.25rem",
  controlHeightIconLg: "2.5rem",
});
