import type { Locale } from "@/paraglide/runtime";

export function controlCopy(locale: Locale) { return locale === "sv" ? sv : en; }
const en = {
  title: "Asset and deferral controls", intro: "Link an existing posted acquisition or opening basis. Then compare known schedules with every entry on the declared control accounts.",
  warning: "Synthetic review only. No ledger entry is created. Source completeness, legal depreciation and financial-close readiness are not established.",
  basis: "Link carrying basis", savedBases: "Retained carrying bases", snapshot: "Capture control snapshot", newSnapshot: "Start a new snapshot request", saved: "Saved control snapshots", open: "Open snapshot", refresh: "Refresh saved records",
  schedule: "Schedule", more: "Load more schedules", choose: "Select a schedule", voucher: "Posted voucher ID", loadVoucher: "Load posted voucher", lines: "Select basis control lines",
  basisHelp: "Select acquisition debits, or imported opening cost debits and accumulated-recognition credits. Their net must equal schedule cost. Do not select cash, supplier, or expense counterpart lines. Linking freezes schedule terms.",
  amounts: "Amounts are integer minor units in the book currency. Original cost = accumulated recognition + carrying amount. Imported history must not restart the schedule.",
  kind: "Basis kind", acquisition: "Acquisition", imported: "Imported opening", date: "Basis posting date", evidence: "Source evidence ID", locator: "Source component locator", reviewEvidence: "Review evidence ID", rationale: "Review rationale", cost: "Original cost", accumulated: "Previously recognized amount", carrying: "Carrying amount / schedule cost", saveBasis: "Retain basis link", operator: "Only an operator can review and link a carrying basis.",
  account: "Account", expected: "Expected register amount", ledger: "Ledger amount", difference: "Difference", unexplained: "Unexplained rows", missing: "Missing expected rows", debit: "Debit", credit: "Credit", line: "Line", asOf: "Include postings through", inventory: "Account-inventory evidence ID", accounts: "Declare carrying control accounts", accountsHelp: "Include every known basis account and schedule credit account. All entries on these accounts are included, including inactive accounts. Do not include schedule expense/debit accounts.",
  capture: "Save control snapshot", invalid: "Check the required dates, identifiers, selected lines and exact minor-unit amounts. Your entries are retained.",
  retry: "After an uncertain response, submit unchanged inputs to keep the same request key while this form is mounted. After reload, inspect saved records before creating another request.",
  savedBasis: "Basis link retained", savedSnapshot: "Control snapshot retained", empty: "No retained records in this book. This does not establish that no assets or deferrals exist.",
  current: "Captured dependencies are unchanged. This is not accounting approval.", historical: "Historical snapshot: dependencies changed or exceed the currentness bound. Retained bytes are unchanged.",
  gaps: "Review gaps remain. Inspect missing bases, reversed or unposted occurrences, and individual ledger differences.", noGaps: "No differences found in this declared scope. Source coverage and legal treatment remain unverified.",
  controls: "Declared-account controls", schedules: "Captured schedules and basis", ledgerLines: "Complete declared-account contributions", occurrences: "Captured occurrences", recognized: "Recognized from schedule", unavailable: "Not established at this date", reversed: "Basis voucher reversed: review required", missingBasis: "No basis linked", download: "Download retained JSON", downloadWarning: "This file contains source references and financial records. Share it only with an authorized reviewer.",
  details: "Inspect retained basis", sequence: "Ledger cutoff", state: "State", effect: "Expected effect", digest: "Snapshot digest", artifactError: "The retained artifact identity, hash or byte length did not match. No download was offered.",
};
const sv: typeof en = {
  title: "Anläggnings- och periodiseringskontroller", intro: "Koppla ett redan bokfört inköp eller ingående värde. Jämför sedan bevarade planer med varje post på de angivna kontrollkontona.",
  warning: "Endast syntetisk granskning. Ingen verifikation skapas. Källtäckning, laglig avskrivning och bokslutsberedskap är inte fastställda.",
  basis: "Koppla bokfört värde", savedBases: "Bevarade värdeunderlag", snapshot: "Skapa kontrollbild", newSnapshot: "Starta en ny begäran om kontrollbild", saved: "Sparade kontrollbilder", open: "Öppna kontrollbild", refresh: "Uppdatera sparade poster",
  schedule: "Plan", more: "Läs fler planer", choose: "Välj en plan", voucher: "Bokförd verifikations ID", loadVoucher: "Läs bokförd verifikation", lines: "Välj underlagets kontrollrader",
  basisHelp: "Välj inköpets debetrader, eller ingående anskaffningsvärde i debet och tidigare redovisning i kredit. Nettot måste motsvara planens kostnad. Välj inte motkonton för bank, leverantör eller kostnad. Kopplingen låser planens villkor.",
  amounts: "Belopp anges som heltal i bokföringsvalutans minsta enhet. Anskaffningsvärde = tidigare redovisat + bokfört värde. Importerad historik får inte starta om planen.",
  kind: "Underlagstyp", acquisition: "Inköp", imported: "Importerat ingående värde", date: "Underlagets bokföringsdatum", evidence: "Källunderlagets ID", locator: "Källkomponentens referens", reviewEvidence: "Granskningsunderlagets ID", rationale: "Granskningsmotivering", cost: "Anskaffningsvärde", accumulated: "Tidigare redovisat belopp", carrying: "Bokfört värde / planens kostnad", saveBasis: "Bevara värdekoppling", operator: "Endast en operatör får granska och koppla värdeunderlag.",
  account: "Konto", expected: "Förväntat registerbelopp", ledger: "Huvudboksbelopp", difference: "Skillnad", unexplained: "Oförklarade rader", missing: "Saknade förväntade rader", debit: "Debet", credit: "Kredit", line: "Rad", asOf: "Ta med bokföringar till och med", inventory: "Kontoförteckningens underlags-ID", accounts: "Ange kontrollkonton för bokfört värde", accountsHelp: "Ta med alla kända underlagskonton och planernas kreditkonton. Alla poster på kontona tas med, även inaktiva konton. Ta inte med planernas kostnads-/debetkonton.",
  capture: "Spara kontrollbild", invalid: "Kontrollera datum, ID, valda rader och exakta belopp i minsta valutaenhet. Dina uppgifter finns kvar.",
  retry: "Efter ett osäkert svar behåller oförändrade uppgifter samma begäransnyckel medan formuläret är öppet. Efter omladdning: läs sparade poster innan du skapar en ny begäran.",
  savedBasis: "Värdekopplingen har bevarats", savedSnapshot: "Kontrollbilden har bevarats", empty: "Inga bevarade poster i boken. Det visar inte att tillgångar eller periodiseringar saknas.",
  current: "Det bevarade underlaget är oförändrat. Detta är inget redovisningsgodkännande.", historical: "Historisk kontrollbild: underlaget har ändrats eller överskrider kontrollgränsen. Bevarade bytes är oförändrade.",
  gaps: "Granskningspunkter återstår. Kontrollera saknade underlag, återförda eller obokförda tillfällen och enskilda huvudboksskillnader.", noGaps: "Inga skillnader hittades inom angivet urval. Källtäckning och laglig behandling är fortfarande obestyrkta.",
  controls: "Kontroller för angivna konton", schedules: "Bevarade planer och underlag", ledgerLines: "Samtliga bidrag på angivna konton", occurrences: "Bevarade tillfällen", recognized: "Redovisat enligt planen", unavailable: "Inte fastställt vid detta datum", reversed: "Underlagsverifikationen är återförd: granskning krävs", missingBasis: "Underlagskoppling saknas", download: "Hämta bevarad JSON", downloadWarning: "Filen innehåller källreferenser och ekonomiska uppgifter. Dela den bara med en behörig granskare.",
  details: "Granska bevarat underlag", sequence: "Huvudboksgräns", state: "Tillstånd", effect: "Förväntad effekt", digest: "Kontrollbildens kontrollsumma", artifactError: "Den bevarade filens identitet, hash eller bytelängd stämde inte. Ingen hämtning erbjöds.",
};
