const en = {
  title: "Accountant review pack",
  owner_sources: "Owner sources",
  owner_controls: "Owner controls",
  expense_tax: "Expense controls",
  providerWarning:
    "Owner amounts are registered positions, not verified openings. Unpaid linked claims are allowed. Expense controls use actual-review mode: exclusions remain visible and no tax contribution is calculated.",
  ownerBalance: "Registered owner positions",
  scale: "scale",
  controlDifference: "Provider account comparisons",
  unresolvedOwner: "Unlinked owner sources",
  outsideOwner: "Owner source outside the control cutoff",
  reviewState: "Review / source state",
  originalAmount: "Source amount (minor units)",
  grossDifference: "Reviewed minus source gross (minor units)",
  netDifference: "Reviewed minus source net (minor units)",
  vatDifference: "Reviewed minus source VAT (minor units)",
  exclusionReasons: "Provider exclusions",
  unknownValue: "Unknown — not zero",
  warning:
    "Synthetic review only. This is not an annual report, tax calculation, company-completeness certificate or a verified Visma format.",
  intro:
    "Capture one ledger and source basis for accountant review. Later changes do not alter saved pages or download bytes.",
  openingWarning:
    "First year does not mean zero opening balances. Recorded opening amounts are not independently verified. Privately paid items and shareholder funding still need evidence and classification.",
  startsOn: "Period starts",
  endsOn: "Period ends",
  opening: "Opening-basis explanation",
  openingEvidence: "Opening evidence IDs (comma separated)",
  notes: "Questions and notes for the accountant",
  exclusionName: "Known source outside this pack (optional)",
  exclusionReason: "Why that source is excluded",
  create: "Create review pack",
  another: "Start a new snapshot version",
  created: "Saved review pack",
  invalid: "Check the dates, explanations and evidence IDs.",
  retry:
    "Retry keeps the same request identity. Start a new version to capture changed records; existing packs remain available.",
  load: "Open review pack",
  packId: "Review pack ID",
  retained: "Retained review packs",
  empty: "No retained review packs.",
  next: "Load more",
  refresh: "Refresh status",
  current:
    "The records captured in this pack are unchanged. Review gaps and unverified opening balances still need attention.",
  historical:
    "Records have changed since this pack was created. Its saved pages and files still show the original snapshot.",
  currentnessUnknown:
    "Current status is unknown. Retained pages and verified files remain available.",
  digest: "Pack digest",
  sequence: "Committed ledger sequence",
  report: "Internal report",
  openingStatus: "Opening basis: not verified",
  balances: "Balances",
  journal: "Journal",
  evidence: "Evidence",
  coverage: "Review gaps",
  downloads: "Review files",
  downloadWarning:
    "Files include sensitive retained evidence. Share only with authorized reviewers. Every CSV starts with a manifest row and uses one leading apostrophe per data cell to protect exact text and prevent spreadsheet formulas. JSON retains the original values.",
  prepareDownload: "Prepare download",
  save: "Save file",
  bytes: "bytes",
  hash: "SHA-256",
  checked: "Download bytes match the retained hash. This is not accounting validation.",
  loaded: "Rows loaded",
  of: "of",
  fullFiles: "Download files include the entire captured section, not only the loaded pages.",
  account: "Account",
  name: "Name",
  recordedOpening: "Recorded opening",
  debit: "Debits",
  credit: "Credits",
  recordedClosing: "Recorded closing",
  part: "Basis",
  voucher: "Voucher",
  date: "Posting date",
  description: "Description",
  receipt: "Receipt / approval",
  refs: "Evidence references",
  inspect: "Inspect retained content",
  disposition: "Included / excluded",
  origin: "Source",
  included: "Included vouchers",
  excluded: "Excluded later vouchers",
  code: "Control",
  status: "State",
  detail: "Review gap",
  basis: "Captured domain dependencies",
  notesTitle: "Accountant questions",
  emptySection:
    "This captured section contains no rows. That does not establish that the obligation is absent.",
};
const sv: typeof en = {
  title: "Granskningspaket för redovisning",
  owner_sources: "Ägarkällor och granskningar",
  owner_controls: "Sparade ägarkontroller",
  expense_tax: "Utgiftskontroller och undantag",
  providerWarning:
    "Ägarbeloppen är registrerade poster, inte verifierade ingående saldon. Obetalda, bokföringslänkade fordringar är tillåtna. Utgiftskontroller använder faktisk granskning: undantag visas och inga skattebidrag beräknas.",
  ownerBalance: "Registrerade ägarposter",
  scale: "decimaler",
  controlDifference: "Modulens kontojämförelser",
  unresolvedOwner: "Ägarkällor utan bokföringslänk",
  outsideOwner: "Ägarkälla utanför kontrollens slutdatum",
  reviewState: "Gransknings- / källäget",
  originalAmount: "Källbelopp (minsta valutaenhet)",
  grossDifference: "Granskat minus källans brutto (minsta valutaenhet)",
  netDifference: "Granskat minus källans netto (minsta valutaenhet)",
  vatDifference: "Granskat minus källans moms (minsta valutaenhet)",
  exclusionReasons: "Modulens undantag",
  unknownValue: "Okänt — inte noll",
  warning:
    "Endast syntetisk granskning. Detta är inte en årsredovisning, skatteberäkning, ett fullständighetsintyg eller ett verifierat Visma-format.",
  intro:
    "Spara en gemensam bokförings- och källgrund för granskning. Senare ändringar påverkar inte sparade sidor eller filernas innehåll.",
  openingWarning:
    "Första året betyder inte att ingående saldon är noll. Bokförda ingående belopp är inte oberoende verifierade. Privat betalda poster och ägarfinansiering behöver fortfarande underlag och klassificering.",
  startsOn: "Periodens början",
  endsOn: "Periodens slut",
  opening: "Förklaring av ingående balans",
  openingEvidence: "Underlags-ID:n för ingående balans (kommatecken)",
  notes: "Frågor och anteckningar till redovisaren",
  exclusionName: "Känd källa utanför paketet (valfritt)",
  exclusionReason: "Varför källan är undantagen",
  create: "Skapa granskningspaket",
  another: "Starta en ny version",
  created: "Sparat granskningspaket",
  invalid: "Kontrollera datum, förklaringar och underlags-ID:n.",
  retry:
    "Ett nytt försök använder samma begäran. Starta en ny version för att fånga ändrade poster. Befintliga paket finns kvar.",
  load: "Öppna granskningspaket",
  packId: "Granskningspaketets ID",
  retained: "Sparade granskningspaket",
  empty: "Inga sparade granskningspaket.",
  next: "Hämta fler",
  refresh: "Uppdatera status",
  current:
    "Vid den senaste lyckade uppdateringen var de sparade beroendena oförändrade. Det bevisar inte fullständighet.",
  historical:
    "Vid den senaste lyckade uppdateringen hade beroendena ändrats. Sparade sidor och filer är oförändrade.",
  currentnessUnknown: "Aktuell status är okänd. Sparade sidor och kontrollerade filer finns kvar.",
  digest: "Paketets kontrollsumma",
  sequence: "Bokförd huvudbokssekvens",
  report: "Intern rapport",
  openingStatus: "Ingående balans: inte verifierad",
  balances: "Bokförda saldon",
  journal: "Verifikationer",
  evidence: "Underlag",
  coverage: "Granskningsfrågor",
  downloads: "Granskningsfiler",
  downloadWarning:
    "Filerna innehåller känsliga sparade underlag. Dela endast med behöriga granskare. Varje CSV börjar med en manifestrad och har en inledande apostrof i varje datacell för att bevara exakt text och förhindra kalkylbladsformler. JSON behåller originalvärdena.",
  prepareDownload: "Förbered hämtning",
  save: "Spara fil",
  bytes: "byte",
  hash: "SHA-256",
  checked: "Filens byte stämmer med sparad kontrollsumma. Detta validerar inte redovisningen.",
  loaded: "Hämtade rader",
  of: "av",
  fullFiles: "Filerna innehåller hela det sparade avsnittet, inte bara hämtade sidor.",
  account: "Konto",
  name: "Namn",
  recordedOpening: "Bokförd ingående balans",
  debit: "Debet",
  credit: "Kredit",
  recordedClosing: "Bokförd utgående balans",
  part: "Grund",
  voucher: "Verifikation",
  date: "Bokföringsdatum",
  description: "Beskrivning",
  receipt: "Kvitto / godkännande",
  refs: "Underlagshänvisningar",
  inspect: "Granska sparat innehåll",
  disposition: "Ingår / undantaget",
  origin: "Källa",
  included: "Ingående verifikationer",
  excluded: "Undantagna senare verifikationer",
  code: "Kontroll",
  status: "Läge",
  detail: "Granskningsfråga",
  basis: "Sparade domänberoenden",
  notesTitle: "Frågor till redovisaren",
  emptySection: "Det sparade avsnittet har inga rader. Det bevisar inte att skyldigheten saknas.",
};
export const reviewCopy = (locale: string) => (locale === "sv" ? sv : en);
