import type { Locale } from "@/paraglide/runtime";
export function vatCopy(locale: Locale) {
  return locale === "sv" ? sv : en;
}
const en = {
  title: "VAT return drafts",
  boundary:
    "Review drafts only. No legal profile is active. These records do not establish source completeness, ledger reconciliation or a filing-ready VAT return.",
  actual: "Company review",
  synthetic: "Calculation example",
  actualBlocked:
    "Actual-company box values are unavailable, not zero. Legal profile activation remains unavailable.",
  facts: "VAT records",
  empty:
    "No VAT facts retained. Record evidence-backed sales or purchases before preparing a draft.",
  create: "Add VAT record",
  revise: "Edit assessment",
  cancel: "Cancel",
  refresh: "Refresh",
  open: "Open",
  save: "Save reviewed fact",
  prepare: "Save VAT draft",
  drafts: "Saved VAT drafts",
  noDrafts: "No saved drafts. Prepare a review draft to retain its source and calculation basis.",
  invalid: "Check the required fields, dates and amounts. Your entries are retained.",
  saved: "Saved. Reopen the retained record to review its history.",
  operator:
    "Only an admitted operator can record reviewed eligibility facts. Operator review does not activate a legal profile.",
  amountHelp:
    "Enter nonnegative integer öre, not kronor. Unknown classification stays unknown. Negative and credit-note components are outside this profile.",
  linksHelp:
    "Select only the posted VAT control lines for this component. Enter line IDs separated by commas. The voucher must cite the source evidence. This does not prove whole-book reconciliation.",
  sourceKey: "Record reference",
  recordClass: "Source class",
  evidenceId: "Source evidence ID",
  sourceLocator: "Invoice / component locator",
  description: "Description",
  reviewEvidenceId: "Review basis evidence ID",
  reviewRationale: "Review rationale",
  treatment: "Treatment",
  netMinor: "Net (öre)",
  vatMinor: "VAT (öre)",
  grossMinor: "Gross (öre)",
  currency: "Currency (blank = unknown)",
  issuedOn: "Invoice issue date",
  receivedOn: "Purchase invoice receipt date",
  suppliedOn: "Supply date",
  taxPointOn: "Reviewed VAT date",
  dateBasis: "Period attribution rationale",
  periodEvidenceId: "Reporting-period evidence ID",
  registration: "VAT registration",
  registrationEvidenceId: "Registration evidence ID",
  method: "VAT accounting method",
  methodEvidenceId: "Method evidence ID",
  domesticEligibility: "Domestic 25% eligibility",
  treatmentEvidenceId: "Treatment evidence ID",
  fullDeduction: "Full purchase deduction",
  deductionEvidenceId: "Deduction evidence ID",
  voucherId: "Posted voucher ID",
  taxLineIds: "Posted VAT line IDs",
  expenseSourceId: "Linked expense source ID",
  expenseSourceDigest: "Linked expense source digest",
  expenseReviewDigest: "Linked expense review digest",
  startsOn: "Period starts",
  endsOn: "Period ends",
  mode: "Draft mode",
  otherBoxes: "Other VAT boxes",
  unknown: "Unknown",
  confirmed: "Explicitly reviewed",
  unsupported: "Unsupported",
  registered: "Registered",
  notRegistered: "Not registered",
  accrual: "Accrual",
  cash: "Cash",
  sale: "Ordinary domestic sale",
  purchase: "Ordinary domestic purchase",
  absence: "Explicitly absent in this synthetic example only",
  importExpense: "Use a current reviewed expense",
  noImport: "Enter a separate source",
  factHistory: "Immutable revision history",
  current: "Source and ledger basis is current.",
  stale:
    "Source or ledger basis changed. This saved draft is unchanged; review and prepare a new draft.",
  download: "Download saved draft JSON",
  boxes: "Synthetic included subtotals — not a complete return",
  box: "Box",
  exact: "Exact (öre)",
  reported: "Reported (kronor)",
  residual: "Difference (öre)",
  unavailable: "Unavailable",
  blockers: "Unresolved controls",
  contributions: "Fact contributions and exclusions",
  state: "Assessment",
  included: "Included in synthetic calculation",
  excluded: "Excluded",
  ledger: "Selected posted VAT lines",
  sourceDifference: "Gross − net − VAT (öre)",
  rateDifference: "VAT × 4 − net (öre)",
  ledgerDifference: "Selected tax lines − VAT (öre)",
  digest: "Basis digest",
  sequence: "Ledger sequence",
  history: "Source history",
  optional: "Blank optional evidence/date fields remain unknown.",
};
const sv: typeof en = {
  ...en,
  title: "Utkast till momsdeklaration",
  boundary:
    "Endast granskningsutkast. Ingen rättslig profil är aktiverad. Underlagens fullständighet, avstämning mot huvudbok och deklarationsklar moms är inte fastställda.",
  actual: "Företagsgranskning",
  synthetic: "Beräkningsexempel",
  actualBlocked:
    "Verkliga företags deklarationsbelopp är inte tillgängliga, inte noll. Rättslig profil kan inte aktiveras här.",
  facts: "Momsunderlag",
  empty:
    "Inga momsfakta har sparats. Registrera underlag för försäljning eller inköp före ett utkast.",
  create: "Lägg till momsunderlag",
  revise: "Redigera bedömning",
  cancel: "Avbryt",
  refresh: "Uppdatera",
  open: "Öppna",
  save: "Spara granskade fakta",
  prepare: "Spara momsutkast",
  drafts: "Sparade momsutkast",
  noDrafts:
    "Inga sparade utkast. Skapa ett granskningsutkast för att behålla underlag och beräkning.",
  invalid: "Kontrollera obligatoriska fält, datum och belopp. Dina uppgifter finns kvar.",
  saved: "Sparat. Öppna posten för att granska historiken.",
  operator:
    "Endast en behörig operatör får registrera granskade fakta. Granskning aktiverar inte en rättslig profil.",
  amountHelp:
    "Ange icke-negativa heltal i öre, inte kronor. Okända klassificeringar förblir okända. Negativa belopp och kreditnotor stöds inte av profilen.",
  linksHelp:
    "Välj endast verifikationens momsrader för denna komponent. Separera rad-ID med kommatecken. Verifikationen måste hänvisa till underlaget. Detta intygar inte hela huvudbokens avstämning.",
  sourceKey: "Underlagsreferens",
  recordClass: "Underlagsklass",
  evidenceId: "Underlagets ID",
  sourceLocator: "Faktura / komponent",
  description: "Beskrivning",
  reviewEvidenceId: "Granskningsunderlagets ID",
  reviewRationale: "Granskningsmotivering",
  treatment: "Behandling",
  netMinor: "Netto (öre)",
  vatMinor: "Moms (öre)",
  grossMinor: "Brutto (öre)",
  currency: "Valuta (tomt = okänt)",
  issuedOn: "Fakturadatum",
  receivedOn: "Ankomstdatum för inköpsfaktura",
  suppliedOn: "Leveransdatum",
  taxPointOn: "Granskat momsdatum",
  dateBasis: "Motivering till period",
  periodEvidenceId: "ID för periodunderlag",
  registration: "Momsregistrering",
  registrationEvidenceId: "ID för registreringsunderlag",
  method: "Momsmetod",
  methodEvidenceId: "ID för metodunderlag",
  domesticEligibility: "Inhemsk behandling med 25 %",
  treatmentEvidenceId: "ID för behandlingsunderlag",
  fullDeduction: "Full avdragsrätt för inköp",
  deductionEvidenceId: "ID för avdragsunderlag",
  voucherId: "Bokförd verifikation, ID",
  taxLineIds: "Bokförda momsrader, ID",
  expenseSourceId: "Länkad kostnadskälla, ID",
  expenseSourceDigest: "Länkad kostnadskällas kontrollsumma",
  expenseReviewDigest: "Länkad kostnadsgransknings kontrollsumma",
  startsOn: "Periodens start",
  endsOn: "Periodens slut",
  mode: "Utkastets läge",
  otherBoxes: "Övriga momsrutor",
  unknown: "Okänt",
  confirmed: "Uttryckligen granskat",
  unsupported: "Stöds inte",
  registered: "Registrerad",
  notRegistered: "Inte registrerad",
  accrual: "Faktureringsmetoden",
  cash: "Bokslutsmetoden",
  sale: "Vanlig inhemsk försäljning",
  purchase: "Vanligt inhemskt inköp",
  absence: "Uttryckligen frånvarande endast i detta syntetiska exempel",
  importExpense: "Använd aktuell granskad kostnad",
  noImport: "Ange separat underlag",
  factHistory: "Oföränderlig versionshistorik",
  current: "Underlag och huvudboksgrund är aktuella.",
  stale:
    "Underlag eller huvudbok har ändrats. Det sparade utkastet är oförändrat; granska och skapa ett nytt.",
  download: "Ladda ned sparat utkast som JSON",
  boxes: "Syntetiska inkluderade delsummor — inte en fullständig deklaration",
  box: "Ruta",
  exact: "Exakt (öre)",
  reported: "Redovisat (kronor)",
  residual: "Differens (öre)",
  unavailable: "Inte tillgängligt",
  blockers: "Olösta kontroller",
  contributions: "Bidrag och undantag per underlag",
  state: "Bedömning",
  included: "Ingår i syntetisk beräkning",
  excluded: "Exkluderad",
  ledger: "Valda bokförda momsrader",
  sourceDifference: "Brutto − netto − moms (öre)",
  rateDifference: "Moms × 4 − netto (öre)",
  ledgerDifference: "Valda momsrader − moms (öre)",
  digest: "Underlagets kontrollsumma",
  sequence: "Huvudbokssekvens",
  history: "Underlagshistorik",
  optional: "Tomma frivilliga underlags- och datumfält förblir okända.",
};
