import type { Locale } from "@/paraglide/runtime";

const en = {
  title: "Reviewed bank allocations",
  warning:
    "Synthetic bank matching only. No payment, posting, invoice settlement or completeness claim for unlisted sources.",
  prepare: "Prepare allocation plan",
  account: "Bank account",
  reason: "Reason for this exact selection",
  acknowledge: "I have reviewed the source identities and possible alternative matches.",
  statement: "Statement ID",
  ordinal: "Source row ordinal",
  voucher: "Posted voucher ID",
  line: "Posted line ID",
  amount: "Signed allocation (minor units)",
  add: "Add allocation leg",
  remove: "Remove leg",
  invalid:
    "Check every identity, ordinal and exact amount. Acknowledge the review before preparing.",
  newPlan: "Start a new plan",
  planId: "Allocation plan ID",
  loadPlan: "Load saved plan",
  refresh: "Refresh saved state",
  approve: "Approve this exact plan",
  execute: "Execute approved allocation",
  review: "I reviewed the frozen capacities, evidence, reason and digest shown above.",
  stale: "Dependencies changed. Prepare and approve a new plan.",
  ready: "Frozen dependencies are current at the last refresh.",
  unknown: "Freshness is unknown until refresh succeeds.",
  done: "Allocation recorded. No ledger posting was created.",
  receipt: "Command receipt",
  digest: "Exact plan digest",
  capacity: "Frozen capacity review",
  source: "Source identity",
  ledger: "Posted line identity",
  total: "Original amount",
  allocated: "Previously allocated",
  remaining: "Unallocated remainder",
  candidates: "Possible posted lines",
  candidateHelp:
    "Candidate counts include unallocated lines with the same sign, account and statement interval. They are not proof of a match. Alternatives are never selected automatically.",
  evidence: "Retained evidence",
  report: "Capacity-aware reconciliation",
  reportId: "Capacity report ID",
  loadReport: "Load saved report",
  runReport: "Save capacity reconciliation",
  starts: "Start date",
  ends: "End date",
  intervalHelp:
    "Use whole statement intervals. Limits: 1000 combined source/ledger rows, 100 statements and 1000 allocation legs.",
  sources: "Retained source residuals",
  lines: "Posted bank-line residuals",
  complete: "Complete for the declared source coverage",
  incomplete: "Balanced, but declared source coverage is incomplete",
  differences: "Differences remain",
  reportFresh: "Report revisions are current.",
  reportStale: "Report is stale. Save a new reconciliation.",
  gaps: "Coverage gaps",
  noGaps: "No gaps in the declared source coverage. Required-source inventory is separate.",
  boundaries: "Opening / closing difference",
  unknownBalance: "Unavailable",
  savedLegs: "Recorded allocation legs",
  version: "Version",
  currency: "Currency / scale",
  approvalExpires: "Approval expires",
  operator: "An operator must approve this exact plan before execution.",
  newReport: "Create another report",
  legacyMatches: "Retained legacy exact matches",
  details: "Saved provenance",
  leg: "Allocation leg",
};
const sv: typeof en = {
  title: "Granskade bankfördelningar",
  warning:
    "Endast syntetisk bankmatchning. Ingen betalning, bokföring, fakturareglering eller fullständighetsgaranti för källor som inte angetts.",
  prepare: "Förbered fördelningsplan",
  account: "Bankkonto",
  reason: "Skäl för det exakta urvalet",
  acknowledge: "Jag har granskat källidentiteterna och möjliga alternativa matchningar.",
  statement: "Kontoutdragets ID",
  ordinal: "Källradens ordningsnummer",
  voucher: "Bokfört verifikations-ID",
  line: "Bokförd rads ID",
  amount: "Fördelning med tecken (minsta valutaenheter)",
  add: "Lägg till fördelningsrad",
  remove: "Ta bort rad",
  invalid:
    "Kontrollera varje identitet, ordningsnummer och exakt belopp. Bekräfta granskningen innan planen förbereds.",
  newPlan: "Börja en ny plan",
  planId: "Fördelningsplanens ID",
  loadPlan: "Hämta sparad plan",
  refresh: "Uppdatera sparat läge",
  approve: "Godkänn den exakta planen",
  execute: "Verkställ godkänd fördelning",
  review: "Jag har granskat frysta kapaciteter, underlag, skäl och kontrollsumman ovan.",
  stale: "Beroenden har ändrats. Förbered och godkänn en ny plan.",
  ready: "Frysta beroenden var aktuella vid senaste uppdateringen.",
  unknown: "Aktualiteten är okänd tills uppdateringen lyckas.",
  done: "Fördelningen har registrerats. Ingen bokföring skapades.",
  receipt: "Kommandokvitto",
  digest: "Planens exakta kontrollsumma",
  capacity: "Granskning av fryst kapacitet",
  source: "Källidentitet",
  ledger: "Bokförd radidentitet",
  total: "Ursprungligt belopp",
  allocated: "Tidigare fördelat",
  remaining: "Återstående belopp",
  candidates: "Möjliga bokförda rader",
  candidateHelp:
    "Antalet kandidater avser ofördelade rader med samma tecken, konto och kontoutdragsintervall. Det bevisar inte en matchning. Alternativ väljs aldrig automatiskt.",
  evidence: "Bevarat underlag",
  report: "Avstämning med fördelningskapacitet",
  reportId: "Kapacitetsrapportens ID",
  loadReport: "Hämta sparad rapport",
  runReport: "Spara kapacitetsavstämning",
  starts: "Startdatum",
  ends: "Slutdatum",
  intervalHelp:
    "Använd hela kontoutdragsintervall. Gränser: totalt 1000 käll-/bokföringsrader, 100 kontoutdrag och 1000 fördelningsrader.",
  sources: "Återstående källbelopp",
  lines: "Återstående belopp på bankrader",
  complete: "Fullständig för angiven källtäckning",
  incomplete: "Balanserad men angiven källtäckning är ofullständig",
  differences: "Differenser återstår",
  reportFresh: "Rapportens revisioner är aktuella.",
  reportStale: "Rapporten är inaktuell. Spara en ny avstämning.",
  gaps: "Luckor i täckningen",
  noGaps: "Inga luckor i angiven källtäckning. Förteckningen över obligatoriska källor är separat.",
  boundaries: "Ingående / utgående differens",
  unknownBalance: "Saknas",
  savedLegs: "Registrerade fördelningsrader",
  version: "Version",
  currency: "Valuta / decimaler",
  approvalExpires: "Godkännandet löper ut",
  operator: "En operatör måste godkänna den exakta planen före verkställande.",
  newReport: "Skapa en ny rapport",
  legacyMatches: "Bevarade exakta matchningar",
  details: "Sparad proveniens",
  leg: "Fördelningsrad",
};

export function settlementCopy(locale: Locale) {
  return locale === "sv" ? sv : en;
}
