import type { Locale } from "@/paraglide/runtime";

export function bankUnmatchCopy(locale: Locale) {
  return locale === "sv"
    ? {
        title: "Ångra bankmatchning",
        help: "Återställ matchningsutrymme utan att ändra bokföring eller fakturabetalningar. Ursprungliga matchningar och kvitton sparas. Hela fördelningen ångras tillsammans.",
        exactMatchHelp:
          "En ångrad exakt matchning måste matchas igen via en ny granskad fördelning. Gamla matchningsidentiteter återanvänds inte.",
        target: "Matchningstyp",
        allocation: "Granskad fördelning",
        exactMatch: "Exakt matchning",
        allocationId: "Fördelningsplanens ID",
        statement: "Kontoutdragets ID",
        ordinal: "Radnummer",
        reason: "Orsak",
        prepare: "Förbered ångring",
        invalid: "Ange en giltig matchning och en orsak.",
        saved: "Sparade ångringsplaner",
        empty: "Inga ångringsplaner finns på den här sidan.",
        refresh: "Uppdatera",
        first: "Första sidan",
        next: "Nästa sida",
        open: "Öppna granskning",
        planId: "Ångringsplanens ID",
        load: "Hämta plan",
        newPlan: "Förbered en annan ångring",
        review: "Granska ångringen",
        digest: "Planens kontrollsumma",
        currency: "Valuta och decimalskala",
        source: "Källrad",
        line: "Bokföringsrad",
        amount: "Belopp att frigöra",
        sourceUsed: "Matchat från källan före ångring",
        lineUsed: "Matchat från bokföringsraden före ångring",
        ready: "Planens underlag är aktuellt. Ångringen kräver mänskligt godkännande.",
        stale:
          "Underlaget är inte aktuellt eller matchningen har redan ångrats. Läs det sparade kvittot eller förbered en ny plan.",
        unknown:
          "Resultatet är inte fastställt. Uppdatera för att läsa det sparade tillståndet; anta inte att ångringen misslyckades.",
        done: "Bankmatchningen har ångrats. Bokföringen och fakturabetalningar är oförändrade. Kör en ny avstämning.",
        acknowledge:
          "Jag har granskat originalunderlaget, alla relationer och beloppen som frigörs.",
        approve: "Godkänn ångring",
        execute: "Ångra bankmatchningen",
        operator: "En behörig operatör måste godkänna planen.",
        expires: "Godkännandet upphör",
        revokeReason: "Orsak till återkallelse",
        revoke: "Återkalla godkännandet",
        receipt: "Sparat kvitto",
        original: "Original och sparat underlag",
        periods: "Berörda öppna perioder",
        sourceRevision: "Källrevision efter ångring",
        historyHelp:
          "Listan visar sparade planer, inte fullständig källtäckning. Uppdatera första sidan för nya planer.",
      }
    : {
        title: "Undo bank matching",
        help: "Release matching capacity without changing journal entries or invoice payments. Original matches and receipts remain saved. Every leg of an allocation is undone together.",
        exactMatchHelp:
          "After undoing an exact match, rematch through a new reviewed allocation. Old exact-match identities cannot be reused.",
        target: "Match type",
        allocation: "Reviewed allocation",
        exactMatch: "Exact match",
        allocationId: "Allocation plan ID",
        statement: "Statement ID",
        ordinal: "Row number",
        reason: "Reason",
        prepare: "Prepare unmatch",
        invalid: "Enter a valid match identity and a reason.",
        saved: "Saved unmatch plans",
        empty: "There are no saved unmatch plans on this page.",
        refresh: "Refresh",
        first: "First page",
        next: "Next page",
        open: "Open review",
        planId: "Unmatch plan ID",
        load: "Load plan",
        newPlan: "Prepare another unmatch",
        review: "Review unmatch",
        digest: "Plan digest",
        currency: "Currency and minor-unit scale",
        source: "Source row",
        line: "Posted line",
        amount: "Amount to release",
        sourceUsed: "Source allocated before unmatch",
        lineUsed: "Posted line allocated before unmatch",
        ready: "The saved basis is current. Human approval is required before unmatching.",
        stale:
          "The basis changed or this match was already undone. Read the retained receipt or prepare a new plan.",
        unknown:
          "The result is not established. Refresh to read saved state; do not assume that unmatching failed.",
        done: "Bank matching undone. Journal entries and invoice payments are unchanged. Prepare a new reconciliation.",
        acknowledge:
          "I reviewed the original evidence, every relationship and the amounts to release.",
        approve: "Approve unmatch",
        execute: "Undo bank matching",
        operator: "An authorized operator must approve this plan.",
        expires: "Approval expires",
        revokeReason: "Revocation reason",
        revoke: "Revoke approval",
        receipt: "Saved receipt",
        original: "Original and saved basis",
        periods: "Affected open periods",
        sourceRevision: "Source revision after unmatch",
        historyHelp:
          "This list contains saved plans, not complete source coverage. Refresh the first page to find new plans.",
      };
}
