export function exchangeRateCopy(locale: "en" | "sv") { return locale === "sv" ? sv : en; }
const en = {
  title: "Manual exchange-rate reviews",
  warning: "Synthetic review only. No foreign-currency invoice, payment, gain/loss or revaluation posting is supported. These records do not establish legal policy or financial-close readiness.",
  policyHelp: "The rate means target major units per one source major unit. Conversion uses the exact effective date and selected current revision. No inversion, nearby-date selection or missing-rate fallback is allowed.",
  roundingHelp: "Nonnegative amounts only. Scale is the number of decimal places in the source currency. The synthetic policy rounds the exact book minor-unit result to the nearest integer, with ties upward. It is not an approved accounting rule.",
  rates: "Saved rate observations", reviews: "Saved conversion reviews", empty: "No records retained.",
  refresh: "Refresh records", open: "Open record", create: "Retain operator-reviewed rate", revise: "Retain new rate revision",
  sourceKey: "Stable observation source key", fromCurrency: "Source currency", toCurrency: "Target book currency",
  effectiveOn: "Rate effective date", retrievedOn: "Source retrieval date", numerator: "Rate numerator", denominator: "Rate denominator",
  evidence: "Source evidence ID", locator: "Source component locator", reviewEvidence: "Operator review evidence ID", rationale: "Review rationale",
  invalid: "Review the required fields. Enter canonical integer amounts and explicit dates, currencies and scales.",
  retry: "After an uncertain response, retry unchanged input. After reload, recover the saved record before starting another request.",
  saved: "Retained. Nothing was posted.", newRate: "Start another observation", history: "Immutable rate revisions",
  revision: "Revision", digest: "Digest", select: "Select revision for conversion", selected: "Selected rate revision",
  stale: "This draft uses a historical revision. Its inputs and retry key are retained. Retry unchanged input to recover an uncertain saved result. New work against this revision will be refused. Discard the draft explicitly before selecting a current revision.",
  draftPinned: "This draft stays bound to your selected revision. Refreshing or opening another observation does not replace it. After an uncertain response, retry unchanged input or recover the saved record before discarding.",
  draftStatusUnknown: "This draft stays bound to its selected observation. That observation is not the one currently displayed, or its live status is unavailable. Inputs and retry keys are retained; the server checks the exact revision on each request.",
  discardDraft: "Discard draft and retry key",
  newConversion: "Start another conversion with this revision",
  conversion: "Capture conversion review", conversionDate: "Conversion date (must match the rate effective date)",
  sourceScale: "Source currency scale (0–6)", amount: "Original amount (integer minor units)",
  amountEvidence: "Original amount evidence ID", capture: "Retain conversion review", policy: "I select synthetic half-up rounding for this nonnegative amount.",
  current: "The selected rate revision and book configuration are still current. This is not posting authority or market-rate freshness.",
  historical: "Historical review. The rate revision or book configuration has changed; retained bytes are unchanged.",
  exact: "Exact book minor-unit fraction", quotient: "Integer quotient before rounding", remainder: "Division remainder numerator", rounded: "Rounded book amount (minor units)",
  residual: "Exact amount minus rounded amount (signed fraction)", download: "Download retained review JSON", artifactError: "The retained conversion artifact failed its identity or integrity check.",
  rateId: "Rate observation ID", reviewId: "Conversion review ID", operator: "Only an operator can retain or revise a manual rate.",
};
const sv: typeof en = {
  title: "Manuella valutakursgranskningar",
  warning: "Endast syntetisk granskning. Bokföring av fakturor, betalningar, kursvinster/-förluster eller omvärdering i utländsk valuta stöds inte. Underlagen fastställer ingen regelpolicy eller bokslutsklarhet.",
  policyHelp: "Kursen anger målets huvudvalutaenheter per en källenhet. Omräkning använder exakt giltighetsdatum och vald aktuell version. Ingen invertering, närliggande dag eller reservkurs används.",
  roundingHelp: "Endast icke-negativa belopp. Skalan är antalet decimaler i källvalutan. Den syntetiska policyn avrundar exakt belopp i bokvalutans minsta enhet till närmaste heltal, med halva steg uppåt. Detta är ingen godkänd redovisningsregel.",
  rates: "Bevarade kursobservationer", reviews: "Bevarade omräkningsgranskningar", empty: "Inga underlag har bevarats.",
  refresh: "Uppdatera underlag", open: "Öppna underlag", create: "Bevara operatörsgranskad kurs", revise: "Bevara ny kursversion",
  sourceKey: "Stabil källnyckel för observationen", fromCurrency: "Källvaluta", toCurrency: "Bokvaluta som mål",
  effectiveOn: "Kursens giltighetsdatum", retrievedOn: "Källans hämtningsdatum", numerator: "Kursens täljare", denominator: "Kursens nämnare",
  evidence: "Källunderlagets ID", locator: "Källkomponentens referens", reviewEvidence: "ID för operatörens granskningsunderlag", rationale: "Motivering",
  invalid: "Kontrollera obligatoriska fält. Ange kanoniska heltalsbelopp och uttryckliga datum, valutor och skalor.",
  retry: "Vid osäkert svar, försök igen med oförändrade uppgifter. Efter omladdning, hämta det bevarade underlaget innan du skapar en ny begäran.",
  saved: "Bevarat. Inget har bokförts.", newRate: "Skapa en annan observation", history: "Oföränderliga kursversioner",
  revision: "Version", digest: "Kontrollsumma", select: "Välj version för omräkning", selected: "Vald kursversion",
  stale: "Utkastet använder en historisk version. Uppgifter och återförsöksnyckel finns kvar. Försök igen med oförändrade uppgifter för att hämta ett osäkert sparat resultat. Nytt arbete mot denna version nekas. Kassera utkastet uttryckligen innan du väljer en aktuell version.",
  draftPinned: "Utkastet förblir kopplat till vald version. Uppdatering eller en annan öppnad observation ersätter det inte. Vid osäkert svar, försök igen med oförändrade uppgifter eller hämta det sparade underlaget innan du kasserar utkastet.",
  draftStatusUnknown: "Utkastet förblir kopplat till vald observation. En annan observation visas nu, eller aktuell status saknas. Uppgifter och återförsöksnycklar finns kvar; servern kontrollerar exakt version vid varje begäran.",
  discardDraft: "Kassera utkast och återförsöksnyckel",
  newConversion: "Starta en ny omräkning med denna version",
  conversion: "Bevara omräkningsgranskning", conversionDate: "Omräkningsdatum (måste motsvara kursens giltighetsdatum)",
  sourceScale: "Källvalutans skala (0–6)", amount: "Ursprungligt belopp (heltal i minsta valutaenhet)",
  amountEvidence: "ID för underlag till ursprungligt belopp", capture: "Bevara omräkningsgranskning", policy: "Jag väljer syntetisk avrundning uppåt vid halva steg för detta icke-negativa belopp.",
  current: "Vald kursversion och bokkonfiguration är fortfarande aktuella. Detta är inte bokföringsbehörighet eller bevis på aktuell marknadskurs.",
  historical: "Historisk granskning. Kursversion eller bokkonfiguration har ändrats; bevarade byte är oförändrade.",
  exact: "Exakt bråk i bokvalutans minsta enhet", quotient: "Heltalskvot före avrundning", remainder: "Divisionsrestens täljare", rounded: "Avrundat bokbelopp (minsta valutaenhet)",
  residual: "Exakt belopp minus avrundat belopp (bråk med tecken)", download: "Ladda ned bevarad granskning som JSON", artifactError: "Identitets- eller integritetskontrollen av omräkningsunderlaget misslyckades.",
  rateId: "Kursobservationens ID", reviewId: "Omräkningsgranskningens ID", operator: "Endast en operatör får bevara eller ändra en manuell kurs.",
};
