import type { Locale } from "@/paraglide/runtime";

const en = {
  company: "Company",
  todo: "To do",
  proposals: "Proposals",
  accounts: "Accounts",
  sales: "Invoicing",
  purchases: "Purchases",
  bookkeeping: "Bookkeeping",
  reports: "Reports",
  tax: "Tax",
  closing: "Year-end",
  settings: "Settings",
  menu: "Menu",
  close: "Close menu",
  vouchers: "Vouchers",
  chart: "Chart of accounts",
  newEntry: "New journal entry",
  ledger: "General ledger",
  welcome: "Hello",
  review: "Review & post",
  continueWork: "Continue working",
  journalTasks: "Journal proposals",
  journalDetail: "Check the source and accounting before posting.",
  emptyTitle: "No journals waiting for review",
  emptyDetail: "New journal proposals appear here when they are prepared.",
  recent: "Recently posted",
  open: "Open proposals",
  viewAll: "View all",
  search: "Search vouchers",
  allPeriods: "All periods",
  noMatches: "No vouchers match these filters.",
  noVouchers: "Your first voucher starts here.",
  noVouchersDetail:
    "Create a journal entry with its source, review the accounts, then post it to the book.",
  voucher: "Voucher",
  date: "Date",
  description: "Description",
  amount: "Amount",
  details: "Record details",
  source: "Source",
  accounting: "Accounting",
  recorded: "Posted",
  balance: "Balance",
  debit: "Debit",
  credit: "Credit",
  bank: "Reconciliation",
  allocations: "Allocations",
  invoices: "Invoices",
  drafts: "Drafts",
  parties: "Customers & suppliers",
  inbox: "Inbox",
  expenses: "Expenses",
  snapshot: "Report snapshots",
  tools: "Advanced tools",
  coverage: "This queue covers journal proposals.",
  ready: "Start a journal entry",
  readyDetail: "Retain a source and prepare the accounting for review.",
  settingsDetail: "Manage the book’s periods, accounts and language.",
  returnVouchers: "Back to vouchers",
};
const sv: typeof en = {
  company: "Bolaget",
  todo: "Att göra",
  proposals: "Förslag",
  accounts: "Konton",
  sales: "Fakturering",
  purchases: "Inköp",
  bookkeeping: "Bokföring",
  reports: "Rapporter",
  tax: "Skatt",
  closing: "Bokslut",
  settings: "Inställningar",
  menu: "Meny",
  close: "Stäng menyn",
  vouchers: "Verifikat",
  chart: "Kontoplan",
  newEntry: "Nytt verifikat",
  ledger: "Huvudbok",
  welcome: "Hej",
  review: "Granska och bokför",
  continueWork: "Fortsätt arbeta",
  journalTasks: "Bokföringsförslag",
  journalDetail: "Kontrollera underlaget och konteringen före bokföring.",
  emptyTitle: "Inga verifikat väntar på granskning",
  emptyDetail: "Nya bokföringsförslag visas här när de har förberetts.",
  recent: "Senast bokfört",
  open: "Öppna förslag",
  viewAll: "Visa alla",
  search: "Sök verifikat",
  allPeriods: "Alla perioder",
  noMatches: "Inga verifikat matchar filtren.",
  noVouchers: "Ditt första verifikat börjar här.",
  noVouchersDetail: "Skapa ett verifikat med underlag, granska konteringen och bokför det sedan.",
  voucher: "Verifikat",
  date: "Datum",
  description: "Beskrivning",
  amount: "Belopp",
  details: "Postuppgifter",
  source: "Underlag",
  accounting: "Kontering",
  recorded: "Bokfört",
  balance: "Saldo",
  debit: "Debet",
  credit: "Kredit",
  bank: "Avstämning",
  allocations: "Matchningar",
  invoices: "Fakturor",
  drafts: "Utkast",
  parties: "Kunder och leverantörer",
  inbox: "Inkorg",
  expenses: "Utgifter",
  snapshot: "Rapportögonblicksbilder",
  tools: "Avancerade verktyg",
  coverage: "Kön omfattar bokföringsförslag.",
  ready: "Skapa ett verifikat",
  readyDetail: "Spara ett underlag och förbered konteringen för granskning.",
  settingsDetail: "Hantera perioder, konton och språk för bokföringen.",
  returnVouchers: "Tillbaka till verifikat",
};
export function frontendCopy(locale: Locale) {
  return locale === "sv" ? sv : en;
}
